import "server-only";
import { topicQuestionSet } from "./topic-set";

const SHARED = "shared_sl_hl" as const;
const HL = "hl_only" as const;

export const UNIT_3_QUESTIONS = [
  ...topicQuestionSet({
    topicCode: "3.1",
    levelRelevance: SHARED,
    short: [
      ["define", "Define gross domestic product. [2 marks]", "The market value of final goods and services produced within a country's borders during a specified period.", "Including intermediate goods separately and thereby double-counting production.", ["gdp", "measurement"]],
      ["distinguish", "Distinguish between nominal GDP and real GDP. [2 marks]", "Nominal GDP values output at current prices, while real GDP adjusts for changes in the price level.", "Describing real GDP as GDP converted into another currency.", ["nominal_real", "gdp"]],
      ["define", "Define the business cycle. [2 marks]", "Recurring fluctuations in actual economic activity around its longer-term trend, including expansions and contractions.", "Defining it as a fixed calendar schedule that repeats identically.", ["business_cycle", "economic_activity"]],
    ],
    ten: [
      ["explain", "Explain why real GDP per capita may be more useful than nominal GDP for comparing living standards over time. [10 marks]", "Inflation adjustment, population and material living standards.", "Real GDP removes price changes and the per-capita measure accounts for population, giving a better indication of average real output or income.", "Claiming the measure captures distribution, leisure and environmental quality automatically.", ["real_gdp_per_capita", "living_standards", "measurement"]],
      ["analyse", "Analyse how the circular flow of income may be affected by an increase in investment. [10 marks]", "Circular flow, investment as an injection, factor income and leakages.", "Higher investment raises firms' expenditure on capital goods and the incomes earned in producing them, increasing flows between firms and households while saving, taxation and imports limit the domestic expansion.", "Treating money flows as identical to physical output or assuming no leakages occur.", ["circular_flow", "investment", "injections_leakages"]],
      ["explain", "Explain why unemployment may rise during a contraction in the business cycle. [10 marks]", "Falling aggregate demand, output and derived demand for labour.", "Lower spending and sales cause firms to cut production, hours and employment, generating cyclical unemployment.", "Assuming every unemployed worker during a contraction is structurally unemployed.", ["business_cycle", "cyclical_unemployment", "aggregate_demand"]],
    ],
    fifteen: [
      ["evaluate", "Evaluate the usefulness of real GDP per capita as a measure of living standards. [15 marks]", "Real output per person, material welfare and measurement limitations.", "The measure tracks average command over produced goods and services, but omits distribution, unpaid work, leisure, environmental damage and many quality changes.", "Judge by purpose, data quality, informal activity, purchasing power, complementary indicators and whether changes are broadly shared.", "Rejecting GDP entirely because it is incomplete rather than assessing its specific uses.", ["gdp", "living_standards", "measurement"]],
      ["discuss", "Discuss whether economic growth necessarily improves a population's well-being. [15 marks]", "Growth, employment, income, public revenue and non-material welfare.", "Growth can raise consumption and fund services, but benefits may be unequal and accompanied by pollution, insecurity or loss of leisure.", "Consider starting income, distribution, sustainability, type of growth, public policy and short-run disruption versus long-run gains.", "Equating higher total GDP with higher well-being for every resident.", ["growth", "wellbeing", "distributional_effect"]],
      ["examine", "Examine the difficulties of comparing GDP between countries. [15 marks]", "Exchange rates, purchasing-power parity, population and national accounting.", "Market exchange rates and price-level differences distort purchasing power, while informal activity, data quality and production boundaries vary.", "Assess whether the comparison concerns total size, average living standards, fiscal capacity or productivity and use suitable complementary measures.", "Assuming conversion at one exchange rate makes national statistics perfectly comparable.", ["international_comparison", "ppp", "measurement"]],
      ["to_what_extent", "To what extent can changes in national income data identify an economy's position in the business cycle? [15 marks]", "Real GDP growth, output gaps and cyclical indicators.", "Falling or accelerating output provides evidence of contraction or expansion, but revisions, trend uncertainty and supply shocks complicate real-time classification.", "Combine GDP with employment, inflation, capacity use and survey data, and distinguish current conditions from later revised estimates.", "Assuming two quarters of any GDP fall fully describe the causes or severity of a cycle.", ["business_cycle", "national_income", "data_limitations"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "3.2",
    levelRelevance: SHARED,
    short: [
      ["define", "Define aggregate demand. [2 marks]", "Total planned spending on domestically produced final goods and services at each average price level over a period.", "Defining aggregate demand as demand for one product or as consumption alone.", ["aggregate_demand", "definition"]],
      ["define", "Define a deflationary gap. [2 marks]", "A situation in which equilibrium real output is below the economy's full-employment or potential level.", "Confusing a deflationary gap with a fall in the price level itself.", ["deflationary_gap", "output_gap"]],
      ["distinguish", "Distinguish between short-run aggregate supply and long-run aggregate supply. [2 marks]", "Short-run aggregate supply reflects output supplied when some input prices are sticky, while long-run aggregate supply represents productive capacity when adjustments are complete.", "Treating both as market supply curves for an individual product.", ["sras", "lras"]],
    ],
    ten: [
      ["explain", "Explain how a fall in consumer confidence may affect real output and the price level. [10 marks]", "Consumption, aggregate demand and short-run equilibrium.", "Lower confidence encourages saving and postponement of purchases, shifting aggregate demand left and tending to reduce output and inflationary pressure.", "Assuming confidence directly reduces productive capacity.", ["consumer_confidence", "aggregate_demand", "demand_shock"]],
      ["analyse", "Analyse the short-run effects of a rise in firms' energy costs on an economy. [10 marks]", "Short-run aggregate supply and cost-push inflation.", "Higher production costs shift short-run aggregate supply left, raising the price level and reducing real output, with employment likely to weaken.", "Describing the shock as demand-pull inflation caused by higher household spending.", ["supply_shock", "cost_push_inflation", "stagflation"]],
      ["explain", "Explain how an increase in investment may affect aggregate demand and long-run productive capacity. [10 marks]", "Investment as an AD component and capital formation.", "Investment raises current spending and output, while successful capital accumulation can raise productivity and potential output over time.", "Assuming all investment immediately raises long-run capacity by the full spending amount.", ["investment", "aggregate_demand", "productive_capacity"]],
    ],
    fifteen: [
      ["evaluate", "Evaluate the view that increases in aggregate demand always cause inflation. [15 marks]", "Aggregate demand, spare capacity, aggregate supply and price pressures.", "The price effect depends on the economy's output gap and supply response; with spare capacity output may rise substantially before strong inflation emerges.", "Consider expectations, bottlenecks, import leakage, time horizon, demand composition and whether supply also changes.", "Assuming any increase in spending has the same inflationary effect at every level of output.", ["aggregate_demand", "inflation", "spare_capacity"]],
      ["discuss", "Discuss the likely effects of a negative supply shock on households, firms and government. [15 marks]", "Cost-push inflation, falling output and stakeholder effects.", "A leftward supply shift raises living and production costs while reducing output, squeezing real incomes, profits or public budgets and creating difficult policy trade-offs.", "Compare sectors and income groups, duration, expectations, import dependence, fiscal exposure and policy responses.", "Assuming all firms gain from higher prices during a supply shock.", ["supply_shock", "stakeholder_effect", "macro_objective_conflict"]],
      ["evaluate", "Evaluate the view that spare capacity is the main influence on how an economy responds to an increase in aggregate demand. [15 marks]", "Spare capacity, short-run aggregate supply, bottlenecks and expectations.", "With usable idle resources, higher aggregate demand can raise real output with less inflation, while limited or mismatched capacity channels more of the change into the price level.", "Judge the amount and type of spare capacity alongside labour skills, imported inputs, expectations, investment, confidence and the time horizon.", "Treating all unemployment and idle capital as immediately suitable for producing the goods whose demand has increased.", ["spare_capacity", "aggregate_demand", "inflation"]],
      ["to_what_extent", "To what extent can aggregate demand and aggregate supply analysis explain stagflation? [15 marks]", "Adverse supply shocks, expectations and macroeconomic equilibrium.", "A negative supply shift can combine higher inflation with lower output, while wage-price dynamics and repeated shocks may prolong the outcome.", "Judge the framework's explanatory value against sectoral differences, institutions, expectations, global transmission and policy credibility.", "Attributing stagflation to excessive aggregate demand alone.", ["stagflation", "supply_shock", "economic_models"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "3.3",
    levelRelevance: SHARED,
    short: [
      ["define", "Define economic growth. [2 marks]", "An increase in an economy's real output or productive capacity over time.", "Defining growth as any increase in the general price level or nominal GDP.", ["economic_growth", "definition"]],
      ["define", "Define full employment. [2 marks]", "A situation in which cyclical unemployment is absent and those willing and able to work at prevailing conditions can find work, allowing for frictional and structural unemployment.", "Equating full employment with literally zero unemployment.", ["full_employment", "unemployment"]],
      ["define", "Define price stability. [2 marks]", "A low and relatively stable rate of change in the general price level, rather than large inflation or deflation.", "Defining price stability as every individual price remaining unchanged.", ["price_stability", "inflation"]],
    ],
    ten: [
      ["explain", "Explain why low and stable inflation may support economic growth. [10 marks]", "Price stability, planning, real interest rates and investment.", "Predictable prices reduce uncertainty and arbitrary redistribution, helping firms and households make longer-term contracts and investment decisions.", "Assuming any positive inflation rate automatically raises real output.", ["inflation", "growth", "confidence"]],
      ["analyse", "Analyse how rapid economic growth may create a conflict with environmental sustainability. [10 marks]", "Growth, resource use, emissions and external costs.", "If growth relies on carbon-intensive production and resource extraction, higher output can increase pollution and depletion unless technology or policy decouples impact.", "Assuming growth must always increase environmental damage in the same proportion.", ["growth", "sustainability", "macro_objective_conflict"]],
      ["explain", "Explain why reducing unemployment may create inflationary pressure. [10 marks]", "Aggregate demand, labour-market tightness and costs.", "Policies or spending that raise employment can push output toward capacity, strengthening wage bargaining and demand-pull pressure, although the effect depends on spare capacity.", "Claiming every fall in unemployment is caused by inflation.", ["unemployment", "inflation", "trade_off"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate whether low unemployment should be the main macroeconomic objective. [15 marks]", "Employment, output, inflation, external balance and welfare.", "Employment raises income, skills and tax revenue, but pursuing demand beyond capacity can conflict with price stability or external balance.", "Judge economic conditions, unemployment type, policy tools, distribution, sustainability and the costs of alternative objectives.", "Assuming all unemployment can be removed by increasing aggregate demand.", ["unemployment", "macro_objectives", "policy_priority"]],
      ["discuss", "Discuss whether economic growth necessarily conflicts with price stability. [15 marks]", "Actual and potential growth, aggregate demand and aggregate supply.", "Demand-led growth near capacity can be inflationary, while productivity-led potential growth may expand output and reduce cost pressure.", "Distinguish short-run recovery from long-run growth and consider expectations, bottlenecks, imports and policy credibility.", "Treating growth in nominal GDP as evidence of rising real output without inflation.", ["growth", "inflation", "macro_objective_conflict"]],
      ["examine", "Examine the economic costs of persistent deflation. [15 marks]", "Falling prices, real debt, postponed spending and unemployment.", "Expected price falls can delay expenditure, raise real debt burdens and weaken profits, generating lower demand and employment.", "Consider beneficial supply-driven price falls, nominal wage flexibility, monetary space, distribution between borrowers and lenders and policy response.", "Assuming any one-month decline in a price index creates a deflationary spiral.", ["deflation", "debt", "unemployment"]],
      ["to_what_extent", "To what extent are conflicts between macroeconomic objectives unavoidable? [15 marks]", "Growth, employment, inflation, equity, sustainability and external balance.", "Short-run demand expansion may trade inflation against unemployment, while some supply-side improvements can advance several objectives together.", "Judge time horizon, starting conditions, policy mix, distributional choices, external shocks and whether objectives are complements at low output.", "Assuming every policy change necessarily improves one objective only by worsening another.", ["macro_objective_conflict", "policy_mix", "short_run_long_run"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "3.4",
    levelRelevance: SHARED,
    short: [
      ["define", "Define absolute poverty. [2 marks]", "A condition in which income or resources are insufficient to meet a defined minimum level of basic needs.", "Defining poverty only by comparison with the average income of the same country.", ["absolute_poverty", "definition"]],
      ["define", "Define relative poverty. [2 marks]", "Having income or resources below a threshold defined relative to typical living standards in the society.", "Treating relative poverty as a fixed global subsistence line.", ["relative_poverty", "definition"]],
      ["define", "Define the Gini coefficient. [2 marks]", "A numerical measure of income or wealth inequality, commonly ranging from zero for complete equality to one for maximum inequality.", "Interpreting a higher coefficient as a higher average income.", ["gini", "inequality_measurement"]],
    ],
    ten: [
      ["explain", "Explain how unemployment may contribute to poverty. [10 marks]", "Labour income, benefits, employability and poverty risk.", "Job loss reduces market income and may erode skills or networks over time, while the poverty effect depends on household resources and social protection.", "Assuming every unemployed person is necessarily below the poverty line.", ["unemployment", "poverty", "labour_market"]],
      ["analyse", "Analyse how a minimum wage may affect income inequality. [10 marks]", "Wage floors, employment, hours and household income.", "Higher pay for covered low-wage workers can compress wage dispersion, but employment, hours, compliance and which households contain affected workers shape overall inequality.", "Assuming all low-income households have a minimum-wage worker in full-time employment.", ["minimum_wage", "inequality", "unintended_consequence"]],
      ["explain", "Explain how investment in education may reduce poverty over time. [10 marks]", "Human capital, productivity, employability and intergenerational mobility.", "Improved skills can raise employment and wages and weaken transmission of disadvantage, although quality and labour demand determine returns.", "Assuming school enrollment alone guarantees productive skills and jobs.", ["education", "poverty", "human_capital"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate cash transfers as a policy to reduce poverty. [15 marks]", "Income support, targeting, incentives and social protection.", "Transfers directly raise disposable income and can protect nutrition, schooling or consumption, but adequacy, coverage and administration determine impact.", "Judge targeting errors, conditionality, work incentives, inflation, fiscal sustainability, delivery systems and comparison with public services.", "Assuming any reduction in measured income poverty proves long-term capability has improved.", ["cash_transfers", "poverty", "policy_effectiveness"]],
      ["discuss", "Discuss whether income inequality is harmful to economic growth. [15 marks]", "Savings, incentives, human capital, demand and institutions.", "Some rewards may encourage investment, while high inequality can restrict education, weaken demand, intensify instability or enable unequal political influence.", "Consider level and source of inequality, mobility, financial access, redistribution design, time horizon and country institutions.", "Assuming correlation between inequality and growth establishes one universal causal direction.", ["inequality", "growth", "institutions"]],
      ["examine", "Examine the strengths and limitations of using the Gini coefficient to compare inequality. [15 marks]", "Summary inequality measures, data and distribution shape.", "A common index supports comparison, but identical coefficients can conceal different distributions and may omit wealth, in-kind benefits or informal income.", "Assess data quality, household size, taxes and transfers, geographic prices, wealth and complementary percentile or poverty measures.", "Interpreting a coefficient as showing which particular groups gained or lost.", ["gini", "measurement", "data_limitations"]],
      ["to_what_extent", "To what extent can economic growth reduce poverty without redistributive policy? [15 marks]", "Growth, employment, wages, structural change and distribution.", "Broad-based labour-intensive growth can raise market incomes and public revenue, but gains may bypass poor households where assets, skills or location constrain participation.", "Judge growth composition, starting inequality, job quality, inflation, public services, institutions and absolute versus relative poverty.", "Assuming a higher average income must lower both absolute and relative poverty.", ["growth", "poverty", "distributional_effect"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "3.5",
    levelRelevance: SHARED,
    short: [
      ["define", "Define monetary policy. [2 marks]", "Central-bank action to influence interest rates, credit conditions or the money supply in pursuit of macroeconomic objectives.", "Defining monetary policy as government decisions about taxation and spending.", ["monetary_policy", "definition"]],
      ["define", "Define an expansionary monetary policy. [2 marks]", "A monetary-policy stance intended to increase aggregate demand, commonly through lower policy interest rates or easier credit conditions.", "Describing higher interest rates used to reduce inflation.", ["expansionary_monetary_policy", "aggregate_demand"]],
      ["define", "Define the policy interest rate. [2 marks]", "The short-term interest rate set or targeted by a central bank to influence wider borrowing, saving and financial conditions.", "Treating it as the exact lending rate charged to every household and firm.", ["interest_rate", "monetary_transmission"]],
    ],
    ten: [
      ["explain", "Explain how a lower policy interest rate may increase aggregate demand. [10 marks]", "Interest rates, consumption, investment, asset prices and exchange rates.", "Cheaper borrowing and lower returns to saving can raise consumption and investment, while possible currency depreciation may increase net exports.", "Assuming every commercial borrowing rate falls immediately by the full policy-rate change.", ["monetary_transmission", "interest_rate", "aggregate_demand"]],
      ["analyse", "Analyse how tighter monetary policy may reduce demand-pull inflation. [10 marks]", "Higher interest rates, credit conditions and aggregate demand.", "Higher borrowing costs and stronger incentives to save reduce interest-sensitive spending, easing excess demand and wage or price pressure with a lag.", "Claiming contractionary policy directly expands productive capacity.", ["contractionary_monetary_policy", "inflation", "time_lags"]],
      ["explain", "Explain why monetary policy may have a weak effect when household and business confidence is low. [10 marks]", "Monetary transmission, expectations, credit demand and liquidity.", "Even with lower rates, pessimistic households may save and firms may avoid investment, while banks can tighten lending standards.", "Assuming a central bank can compel private borrowers to spend whenever it cuts rates.", ["confidence", "monetary_transmission", "liquidity_trap"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate the effectiveness of monetary policy in reducing inflation. [15 marks]", "Interest-rate transmission, aggregate demand, expectations and inflation sources.", "Tighter policy can moderate demand and anchor expectations, but acts with lags and may be less effective against supply-driven inflation.", "Judge inflation source, credibility, debt exposure, exchange-rate effects, financial stability, policy lags and costs to output and employment.", "Assuming all inflation is caused by excessive domestic credit growth.", ["monetary_policy", "inflation", "policy_effectiveness"]],
      ["discuss", "Discuss whether expansionary monetary policy is likely to reduce unemployment during a recession. [15 marks]", "Interest rates, aggregate demand and cyclical unemployment.", "Lower rates can stimulate spending and output, raising labour demand, but weak confidence, damaged banks or structural unemployment may limit employment gains.", "Consider spare capacity, borrower balance sheets, zero-lower-bound constraints, time lags, labour mismatch and fiscal policy support.", "Assuming lower rates directly retrain workers or remove structural unemployment.", ["monetary_policy", "unemployment", "spare_capacity"]],
      ["examine", "Examine how monetary policy may affect an economy through the exchange rate. [15 marks]", "Interest-rate differentials, capital flows, exchange rates, net exports and imported inflation.", "Lower relative interest returns may weaken the currency, supporting net exports but raising import costs and inflation; the reverse may follow tightening.", "Assess expectations, exchange-rate regime, trade elasticities, foreign-currency debt, global policy and the relative size of expenditure-switching effects.", "Assuming a policy-rate change fixes the exchange rate at a predictable level.", ["monetary_policy", "exchange_rate", "open_economy"]],
      ["to_what_extent", "To what extent should central banks rely on unconventional monetary policy when interest rates are very low? [15 marks]", "Asset purchases, forward guidance, credit channels and low-rate constraints.", "Purchasing assets or guiding expectations can lower longer-term yields and support liquidity when conventional rate cuts are limited.", "Judge transmission to real spending, distributional and asset-price effects, fiscal interaction, exit risks, credibility and banking conditions.", "Assuming creation of central-bank reserves necessarily produces equal growth in bank lending and inflation.", ["unconventional_monetary_policy", "zero_lower_bound", "policy_effectiveness"], HL],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "3.6",
    levelRelevance: SHARED,
    short: [
      ["define", "Define fiscal policy. [2 marks]", "Government decisions about taxation and public expenditure used to influence economic activity and other policy objectives.", "Defining fiscal policy as central-bank control of interest rates.", ["fiscal_policy", "definition"]],
      ["define", "Define an automatic stabilizer. [2 marks]", "A tax or spending mechanism that changes automatically with economic activity and moderates fluctuations without a new policy decision.", "Describing any discretionary stimulus package announced during a recession.", ["automatic_stabilizer", "business_cycle"]],
      ["define", "Define a budget deficit. [2 marks]", "A situation in which government expenditure exceeds government revenue over a specified period.", "Confusing the annual deficit with the accumulated stock of public debt.", ["budget_deficit", "government_finance"]],
    ],
    ten: [
      ["explain", "Explain how expansionary fiscal policy may reduce a deflationary gap. [10 marks]", "Government spending, taxation, disposable income and aggregate demand.", "Higher public spending raises aggregate demand directly, while lower taxes can increase household disposable income and consumption, raising output and employment when spare capacity exists.", "Assuming every unit of a tax cut is spent domestically or that higher demand immediately raises productive capacity.", ["expansionary_fiscal_policy", "deflationary_gap", "aggregate_demand"]],
      ["analyse", "Analyse how automatic stabilizers may reduce fluctuations in economic activity. [10 marks]", "Progressive taxes, unemployment benefits and disposable income.", "During downturns tax payments fall and transfers rise, cushioning household income and demand; the process reverses during booms.", "Assuming automatic stabilizers eliminate the business cycle or require a new vote each time.", ["automatic_stabilizer", "business_cycle", "disposable_income"], HL],
      ["explain", "Explain how contractionary fiscal policy may affect inflation and unemployment. [10 marks]", "Taxation, government spending and aggregate demand.", "Lower public spending or higher taxes reduces aggregate demand, easing demand-pull inflation but tending to lower output and raise cyclical unemployment in the short run.", "Claiming contractionary fiscal policy directly reduces production costs.", ["contractionary_fiscal_policy", "inflation", "unemployment"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate fiscal policy as a response to a recession. [15 marks]", "Discretionary stimulus, aggregate demand and public debt.", "Targeted spending or tax relief can support demand and employment, especially with spare capacity, but implementation lags, saving, imports and financing conditions affect impact.", "Judge policy timing, spending and consumption responses, monetary response, debt sustainability, supply constraints, targeting and the nature of the recession.", "Assuming a larger headline deficit measures the discretionary stimulus exactly.", ["fiscal_policy", "recession", "policy_effectiveness"]],
      ["discuss", "Discuss whether governments should balance their budgets over the economic cycle. [15 marks]", "Cyclical deficits, debt sustainability, fiscal space and stabilization.", "Allowing deficits in downturns and surpluses in strong periods can stabilize demand, but estimating the cycle and sustaining political discipline are difficult.", "Consider borrowing cost, debt level, investment, ageing, shocks, fiscal rules and distinction between current and capital spending.", "Treating a balanced budget as automatically neutral for aggregate demand.", ["budget_balance", "business_cycle", "fiscal_rules"]],
      ["examine", "Examine how the size of the fiscal multiplier may influence government policy choices. [15 marks]", "Multiplier process, leakages, spare capacity and monetary accommodation.", "A larger multiplier gives stronger output effects per unit of fiscal change, while saving, taxation, imports and crowding out reduce successive spending rounds.", "Assess policy instrument, openness, economic slack, expectations, financing, central-bank response and temporary versus permanent measures.", "Assuming one fixed multiplier applies to all countries, times and fiscal instruments.", ["multiplier", "fiscal_policy", "assumptions"], HL],
      ["to_what_extent", "To what extent does high public debt limit the use of expansionary fiscal policy? [15 marks]", "Debt dynamics, borrowing costs, credibility and fiscal space.", "High debt may raise risk premia or political constraints, yet low interest costs, credible institutions and high-return stimulus can preserve room to act.", "Judge currency denomination, maturity, investor base, growth-interest differential, recession severity, monetary conditions and policy composition.", "Assuming a particular debt-to-GDP ratio has the same consequences in every economy.", ["public_debt", "fiscal_space", "policy_effectiveness"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "3.7",
    levelRelevance: SHARED,
    short: [
      ["define", "Define a supply-side policy. [2 marks]", "A policy intended to increase productive capacity, productivity, flexibility or efficiency on the supply side of an economy.", "Defining it as any policy that increases demand for goods.", ["supply_side_policy", "definition"]],
      ["distinguish", "Distinguish between market-based and interventionist supply-side policies. [2 marks]", "Market-based policies strengthen incentives and market flexibility, while interventionist policies use government provision, investment or direction to raise capacity.", "Treating all supply-side policies as deregulation or privatization.", ["market_based", "interventionist"]],
      ["define", "Define labour productivity. [2 marks]", "Output produced per unit of labour input, such as per worker or per hour worked.", "Equating labour productivity with the total number of workers employed.", ["productivity", "labour"]],
    ],
    ten: [
      ["explain", "Explain how investment in education and training may increase long-run aggregate supply. [10 marks]", "Human capital, productivity, employability and productive capacity.", "Improved skills can raise output per worker, adaptability and labour-force participation, reducing structural constraints over time.", "Assuming spending on training immediately produces equally valuable skills for every worker.", ["education", "human_capital", "lras"]],
      ["analyse", "Analyse how reducing business regulation may affect productive capacity. [10 marks]", "Compliance costs, entry, competition, investment and market failure.", "Well-chosen deregulation can lower costs and barriers, encouraging entry and innovation, but removal of protective rules may create external or information costs.", "Assuming every regulation is unnecessary and only raises cost.", ["deregulation", "productive_capacity", "government_failure"]],
      ["explain", "Explain how improved transport infrastructure may affect aggregate supply. [10 marks]", "Infrastructure, transaction costs, labour mobility and productivity.", "Faster and more reliable transport can reduce delivery costs, widen labour markets and support private investment, increasing short- and long-run supply.", "Assuming infrastructure spending raises capacity regardless of project selection or congestion.", ["infrastructure", "productivity", "investment"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate education and training as a supply-side policy. [15 marks]", "Human capital, productivity, structural unemployment and growth.", "Better skills can raise productivity and match workers to changing jobs, but benefits arrive slowly and depend on quality and labour demand.", "Judge targeting, completion, skill relevance, opportunity cost, migration, employer participation and distribution of access.", "Assuming more years in education always cause proportionate productivity growth.", ["education", "supply_side_policy", "time_lags"]],
      ["discuss", "Discuss whether market-based supply-side policies are likely to improve living standards. [15 marks]", "Competition, incentives, flexibility, productivity and distribution.", "Tax reform, deregulation or privatization may improve efficiency and investment, but weaker protections or unequal gains can offset average income growth.", "Consider initial institutions, market power, externalities, public-service quality, time horizon and real-income distribution.", "Equating a rise in potential GDP with improved living standards for all households.", ["market_based_policy", "living_standards", "distributional_effect"]],
      ["examine", "Examine the role of infrastructure investment in achieving long-run economic growth. [15 marks]", "Public capital, productivity, crowding in and network effects.", "Reliable transport, energy and digital systems lower economy-wide costs and can unlock complementary private investment.", "Assess project appraisal, financing, maintenance, regional balance, environmental effects, construction bottlenecks and governance.", "Assuming every large construction project is productive infrastructure.", ["infrastructure", "growth", "government_failure"]],
      ["to_what_extent", "To what extent can supply-side policies reduce inflation without increasing unemployment? [15 marks]", "Productivity, productive capacity, structural reform and cost pressure.", "Policies that lower unit costs or expand capacity can reduce inflationary pressure while supporting employment, but implementation can displace workers and takes time.", "Judge the policy type, source of inflation, transition support, labour mobility, demand conditions, time horizon and distributional effects.", "Assuming supply-side reforms can quickly offset any temporary imported inflation shock.", ["supply_side_policy", "inflation", "unemployment"]],
    ],
  }),
];
