import "server-only";
import { topicQuestionSet } from "./topic-set";

const SHARED = "shared_sl_hl" as const;
const HL = "hl_only" as const;

export const UNIT_2_QUESTIONS = [
  ...topicQuestionSet({
    topicCode: "2.1",
    levelRelevance: SHARED,
    short: [
      ["define", "Define demand. [2 marks]", "The quantity of a good or service consumers are willing and able to buy at a given price over a specified period.", "Describing desire alone without willingness and ability to purchase.", ["demand", "definition"]],
      ["describe", "Describe the law of demand. [2 marks]", "Ceteris paribus, quantity demanded rises when price falls and falls when price rises.", "Describing a shift of the demand curve rather than movement along it caused by price.", ["law_of_demand", "price_change"]],
      ["distinguish", "Distinguish between a substitute and a complement in consumption. [2 marks]", "A substitute can replace another good, whereas a complement is consumed jointly with another good.", "Defining both only by whether their prices are high or low.", ["related_goods", "demand_determinants"]],
    ],
    ten: [
      ["explain", "Explain why a fall in the price of a normal good may increase its quantity demanded. [10 marks]", "The law of demand, income and substitution effects, and diminishing marginal benefit.", "A lower relative price encourages substitution toward the good and raises consumers' real purchasing power, producing a movement along demand.", "Calling the price-induced movement an increase in demand rather than an increase in quantity demanded.", ["price_change", "income_effect", "substitution_effect"]],
      ["analyse", "Analyse how an increase in household income may affect demand for different types of goods. [10 marks]", "Normal, inferior and luxury goods and income elasticity of demand.", "Higher income tends to shift demand right for normal goods, may shift it left for inferior goods, and can cause proportionately larger changes for income-elastic luxuries.", "Assuming income growth raises demand for every good by the same proportion.", ["income_change", "normal_inferior", "distributional_effect"]],
      ["explain", "Explain how expectations of future prices can affect current demand. [10 marks]", "Intertemporal choice and non-price determinants of demand.", "Expected price rises can bring planned purchases forward, while expected falls can postpone demand; durability, credit and necessity condition the response.", "Treating expectations as a movement along an unchanged demand curve.", ["expectations", "intertemporal_choice"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate the view that price is the most important determinant of demand for a product. [15 marks]", "Price movements, non-price demand determinants and elasticity.", "Price changes alter quantity demanded, while income, tastes, expectations, demographics and related-good prices can shift the whole demand curve.", "Judge relative importance by product, time horizon, necessity, market conditions and the size and persistence of non-price shocks.", "Comparing a movement along demand with a demand shift as if they were the same event.", ["demand_determinants", "elasticity", "assumptions"]],
      ["discuss", "Discuss how changing consumer tastes may affect prices and output in a competitive market. [15 marks]", "Demand shifts and market adjustment.", "A favourable taste shift creates excess demand at the initial price, encouraging higher price and expanded output until a new equilibrium is reached.", "Consider supply elasticity, adjustment time, expectations, producer capacity and whether the change in tastes persists.", "Assuming demand changes alter price but never quantity supplied.", ["consumer_tastes", "market_adjustment", "short_run_long_run"]],
      ["evaluate", "Using real-world examples, evaluate the view that expectations about future prices are the most important influence on current demand. [15 marks]", "Expected future prices as a non-price determinant of current demand, compared with other demand determinants.", "An expected future price increase may shift current demand right as consumers buy sooner, while an expected fall may delay purchases and shift current demand left; the strength of the effect varies across markets.", "Compare expectations with income, preferences, population and related-good prices, considering how storability, durability, necessity, credit constraints and the accuracy of expectations affect their relative importance.", "Treating expectations as a movement along the demand curve or assuming every expected future price change produces the same current response.", ["price_expectations", "demand_determinants", "market_context"]],
      ["to_what_extent", "To what extent can firms influence demand for their products? [15 marks]", "Advertising, branding, product differentiation and demand determinants.", "Marketing and differentiation can shift demand and reduce perceived substitutability, but income, competitors, regulation and underlying preferences constrain firms.", "Assess market structure, credibility, network effects, product type, campaign cost and whether influence creates lasting loyalty.", "Assuming advertising guarantees higher sales regardless of price or competitors.", ["advertising", "product_differentiation", "market_power"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "2.2",
    levelRelevance: SHARED,
    short: [
      ["define", "Define supply. [2 marks]", "The quantity of a good or service producers are willing and able to offer for sale at a given price over a specified period.", "Describing the stock of a product rather than the quantity offered at a particular price and time.", ["supply", "definition"]],
      ["describe", "Describe the law of supply. [2 marks]", "Ceteris paribus, quantity supplied rises when price rises and falls when price falls.", "Describing a shift of supply caused by costs rather than movement along supply caused by price.", ["law_of_supply", "price_change"]],
      ["define", "Define joint supply. [2 marks]", "A production relationship in which producing one good also produces another good from the same process.", "Confusing joint supply with complementary goods in consumption.", ["joint_supply", "production"]],
    ],
    ten: [
      ["explain", "Explain how a rise in firms' energy costs may affect the supply of a product. [10 marks]", "Costs of production and shifts in supply.", "Higher variable costs reduce profitability at each output price, shifting supply left and changing market price and quantity depending on demand.", "Treating higher costs as a movement along the original supply curve.", ["costs", "supply_shift"]],
      ["analyse", "Analyse how an improvement in production technology may affect market supply. [10 marks]", "Productivity, unit costs and supply.", "Technology can raise output per input and lower marginal or average costs, making more output profitable at each price and shifting supply right.", "Assuming every new technology immediately lowers costs for all producers equally.", ["technology", "productivity", "short_run_long_run"]],
      ["explain", "Explain why the supply of an agricultural product may vary between seasons. [10 marks]", "Natural conditions, production lags, inventories and seasonal supply.", "Weather and biological production cycles alter harvests, while storage and expectations can redistribute supply across time.", "Assuming seasonal supply changes are caused only by a change in the product's current price.", ["agriculture", "time_lags", "expectations"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate the view that production costs are the main influence on market supply. [15 marks]", "Costs, technology, taxes, subsidies, expectations and producer numbers.", "Costs affect profitability at each price, but capacity, innovation, regulation, shocks and expected future prices may dominate in particular markets.", "Judge by industry, time horizon, cost structure, entry conditions and the magnitude and duration of competing influences.", "Assuming any cost rise reduces physical productive capacity by the same amount.", ["costs", "supply_determinants", "short_run_long_run"]],
      ["discuss", "Discuss how disruptions to global supply chains may affect market supply in the short run and the long run. [15 marks]", "Input availability, production costs, inventories and supply-chain adjustment.", "A disruption can raise costs or stop access to key inputs, shifting supply left; over time firms may change suppliers, redesign products, invest in capacity or hold larger inventories.", "Compare industries by input concentration, substitutability, inventories, market power and the cost and resilience of alternative supply arrangements.", "Assuming every supply-chain disruption permanently reduces productive capacity by the same amount.", ["supply_chain", "supply_shift", "short_run_long_run"]],
      ["examine", "Examine how expectations of future market conditions may influence current supply. [15 marks]", "Intertemporal supply decisions, inventories and investment.", "Expected future price rises may encourage storage and reduce current supply, while favourable long-run demand can stimulate capacity investment that later expands supply.", "Distinguish current inventory decisions from future productive capacity and consider perishability, finance and uncertainty.", "Assuming all expected price rises necessarily increase current supply.", ["expectations", "inventories", "investment"]],
      ["to_what_extent", "To what extent can government policy increase the supply of an essential good? [15 marks]", "Subsidies, tax relief, infrastructure, regulation and public provision.", "Policies can lower costs or raise capacity, shifting supply right, but fiscal cost, targeting, time lags and shortages of key inputs can limit results.", "Judge effectiveness by supply elasticity, administrative capacity, opportunity cost, market power and whether increased supply reaches intended users.", "Equating a subsidy paid to producers with a guaranteed equal fall in consumer price.", ["government_intervention", "essential_goods", "policy_effectiveness"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "2.3",
    levelRelevance: SHARED,
    short: [
      ["define", "Define competitive market equilibrium. [2 marks]", "The price and quantity at which quantity demanded equals quantity supplied, so there is no tendency for price to change.", "Defining equilibrium as a situation in which every consumer and producer is satisfied with the outcome.", ["equilibrium", "definition"]],
      ["define", "Define excess demand. [2 marks]", "A shortage at a given price where quantity demanded exceeds quantity supplied.", "Calling any high level of demand excess demand without comparing it with quantity supplied at that price.", ["shortage", "disequilibrium"]],
      ["define", "Define consumer surplus. [2 marks]", "The difference between what consumers are willing to pay and what they actually pay.", "Confusing consumer surplus with the firm's profit or the consumer's unspent income.", ["consumer_surplus", "welfare"]],
    ],
    ten: [
      ["explain", "Explain how a competitive market may adjust from a shortage to equilibrium. [10 marks]", "Excess demand, price signals and movements along demand and supply.", "A shortage creates upward pressure on price; higher price reduces quantity demanded and increases quantity supplied until they are equal.", "Shifting demand and supply curves when only market price is adjusting.", ["shortage", "price_mechanism", "market_adjustment"]],
      ["analyse", "Analyse the effects of an increase in demand when market supply is relatively inelastic. [10 marks]", "Demand shifts, supply elasticity and equilibrium.", "A rightward demand shift against an inelastic supply produces a relatively large price rise and a smaller increase in equilibrium quantity.", "Assuming inelastic supply prevents any change in quantity or makes price fall.", ["demand_shift", "supply_elasticity", "incidence"]],
      ["explain", "Explain how a fall in supply may affect consumer and producer surplus. [10 marks]", "Market equilibrium and welfare surpluses.", "A leftward supply shift generally raises price and lowers quantity, reducing consumer surplus; the effect on producer surplus depends on the cause and cost change.", "Claiming producer surplus must rise merely because the market price rises.", ["supply_shift", "consumer_surplus", "producer_surplus"]],
    ],
    fifteen: [
      ["evaluate", "Evaluate the view that competitive market equilibrium always produces the best outcome for society. [15 marks]", "Allocative efficiency, consumer and producer surplus, market failure and equity.", "Under suitable assumptions equilibrium can maximize total surplus, but externalities, information problems, market power and unequal income can separate private exchange from social welfare.", "Judge against efficiency and equity objectives, the realism of assumptions and the feasibility and costs of intervention.", "Treating equilibrium as automatically equitable because quantity demanded equals quantity supplied.", ["allocative_efficiency", "market_failure", "equity"]],
      ["discuss", "Using real-world examples, discuss how a sudden increase in demand affects different stakeholders in a market. [15 marks]", "Market adjustment, surplus and stakeholder effects.", "Higher demand tends to raise price and quantity, benefiting some producers while reducing affordability for existing consumers and attracting resources or entry.", "Consider supply elasticity, inventories, time horizon, producer costs, consumer income and possible external effects.", "Assuming all producers gain equally from a price rise regardless of costs or capacity.", ["stakeholder_effect", "demand_shock", "short_run_long_run"]],
      ["examine", "Examine why the price mechanism may adjust slowly after a major supply disruption. [15 marks]", "Prices, information, contracts, inventories and factor mobility.", "Price changes signal scarcity and ration demand, but fixed contracts, regulation, incomplete information, production lags and bottlenecks can delay reallocation.", "Compare immediate rationing with longer-run entry, substitution and capacity expansion, including social costs of rapid price adjustment.", "Assuming a flexible price by itself instantly creates additional physical supply.", ["supply_shock", "price_mechanism", "time_lags"]],
      ["to_what_extent", "To what extent does a higher market price solve the problem of excess demand? [15 marks]", "Shortages, rationing, demand and supply responses.", "A higher price reduces quantity demanded and encourages supply, tending to clear the market, but it may exclude low-income consumers or fail where supply cannot respond.", "Assess elasticity, essentiality, adjustment time, information, price controls and equity before judging whether clearing is a satisfactory solution.", "Equating market clearing with meeting every consumer's need.", ["shortage", "rationing", "equity"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "2.4",
    levelRelevance: HL,
    short: [
      ["define", "Define utility maximization. [2 marks]", "Choosing the affordable combination of goods and services expected to provide the greatest total satisfaction or benefit.", "Equating utility maximization with buying the largest physical quantity of goods.", ["utility", "consumer_choice"]],
      ["define", "Define profit maximization. [2 marks]", "Producing or choosing actions that make the difference between total revenue and total cost as large as possible.", "Defining it as maximizing revenue without considering costs.", ["profit", "producer_behaviour"]],
      ["define", "Define satisficing behaviour. [2 marks]", "Choosing an option that is good enough to meet an acceptable threshold rather than searching for the theoretical maximum.", "Treating satisficing as random choice with no objective or constraint.", ["satisficing", "bounded_rationality"]],
    ],
    ten: [
      ["explain", "Explain why a consumer may not maximize utility when making a purchase. [10 marks]", "Bounded rationality, imperfect information, habits and behavioural influences.", "Limited time and information, framing, heuristics or social norms can make choices depart from the fully informed optimizing model.", "Assuming any choice later regretted proves the consumer was irrational at the time.", ["bounded_rationality", "consumer_behaviour", "information"]],
      ["analyse", "Analyse why a firm may pursue objectives other than profit maximization. [10 marks]", "Separation of ownership and control, growth, market share, survival and social objectives.", "Managers and owners can have different incentives, while long-run strategy, risk and stakeholder commitments may make other objectives relevant.", "Assuming a non-profit objective means the firm can ignore all financial constraints.", ["firm_objectives", "principal_agent", "stakeholder_effect"]],
      ["explain", "Explain how behavioural biases may affect consumer demand. [10 marks]", "Anchoring, framing, default effects, social norms and bounded rationality.", "Biases can change perceived value or ease of choice, shifting demand even when underlying prices and income are unchanged.", "Treating every stable preference as evidence of a cognitive bias.", ["behavioural_bias", "demand_shift", "choice_architecture"]],
    ],
    fifteen: [
      ["evaluate", "Evaluate the usefulness of the assumption that consumers maximize utility. [15 marks]", "Utility maximization, budget constraints and behavioural economics.", "The assumption gives clear predictions about demand and trade-offs, but bounded rationality, social preferences and inconsistent choices may weaken descriptive accuracy.", "Judge usefulness by predictive purpose, market context, aggregation, empirical evidence and whether simpler models outperform alternatives.", "Rejecting a model solely because no consumer consciously calculates marginal utility.", ["utility", "assumptions", "behavioural_economics"]],
      ["discuss", "Discuss whether profit maximization is likely to remain the main objective of large firms. [15 marks]", "Profit, ownership, management incentives, growth and stakeholder objectives.", "Profit supports survival and investor returns, yet managerial goals, regulation, reputation and environmental commitments can redirect decisions.", "Distinguish short-run from long-run profit, stated from revealed objectives, and competitive from protected markets.", "Assuming corporate social responsibility and profitability are necessarily opposites.", ["firm_objectives", "short_run_long_run", "stakeholder_effect"]],
      ["examine", "Using real-world examples, examine how choice architecture may influence economic decisions. [15 marks]", "Defaults, framing, nudges and bounded rationality.", "Changing how options are presented can alter take-up without changing prices or removing choice, potentially correcting predictable decision errors.", "Consider effectiveness, persistence, heterogeneity, manipulation, autonomy and comparison with taxes, regulation or information provision.", "Claiming a nudge forces the same decision on every individual.", ["choice_architecture", "nudge", "government_failure"]],
      ["to_what_extent", "To what extent does behavioural economics weaken the traditional model of rational economic decision-making? [15 marks]", "Rational choice, bounded rationality, heuristics and behavioural evidence.", "Systematic biases challenge complete information and consistent optimization, while traditional models may still predict aggregate responses and provide useful benchmarks.", "Judge by decision type, stakes, learning, market discipline and whether behavioural alternatives offer clearer testable predictions.", "Treating rationality as requiring perfect outcomes rather than internally consistent choices under constraints.", ["bounded_rationality", "assumptions", "economic_models"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "2.5",
    levelRelevance: SHARED,
    short: [
      ["define", "Define price elasticity of demand. [2 marks]", "The responsiveness of quantity demanded to a change in price, measured as the percentage change in quantity demanded divided by the percentage change in price.", "Describing the slope of demand without reference to proportional responsiveness.", ["ped", "definition"]],
      ["define", "Define income elasticity of demand. [2 marks]", "The responsiveness of demand to a change in consumer income, measured as the percentage change in quantity demanded divided by the percentage change in income.", "Confusing income elasticity with the income effect of a change in the good's own price.", ["yed", "definition"]],
      ["define", "Define cross-price elasticity of demand. [2 marks]", "The responsiveness of demand for one good to a change in the price of another good.", "Using the good's own price in both parts of the relationship.", ["xed", "related_goods"]],
    ],
    ten: [
      ["explain", "Explain why demand for a necessity is often price inelastic. [10 marks]", "Price elasticity of demand, necessity and availability of substitutes.", "Consumers have limited ability to reduce or replace essential consumption, particularly in the short run and when it takes a small income share.", "Claiming necessity alone makes demand perfectly inelastic in every context.", ["ped", "necessity", "substitutes"]],
      ["analyse", "Analyse how price elasticity of demand affects a firm's total revenue after a price change. [10 marks]", "Price elasticity and total revenue.", "For elastic demand the percentage quantity response exceeds the price change, so price and revenue move oppositely; for inelastic demand they tend to move together.", "Using the sign of PED mechanically without explaining the relative percentage changes.", ["ped", "total_revenue", "firm_decision"]],
      ["explain", "Explain how income elasticity of demand may influence firms' production plans during economic growth. [10 marks]", "Income elasticity, normal and inferior goods, and demand forecasting.", "Expected income growth raises demand more strongly for income-elastic goods, may raise it modestly for necessities and may reduce demand for inferior goods.", "Assuming a positive income elasticity is always greater than one.", ["yed", "growth", "business_planning"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate the importance of price elasticity of demand to firms when setting prices. [15 marks]", "PED, revenue, costs, market power and pricing objectives.", "Estimated elasticity helps predict the quantity and revenue response to price, but profit also depends on cost changes, competitors, capacity and longer-run reactions.", "Judge by data quality, market segment, time horizon, dynamic competitor responses and whether the firm maximizes profit or another objective.", "Assuming the revenue-maximizing price must also maximize profit.", ["ped", "pricing", "firm_decision"]],
      ["discuss", "Discuss how price elasticity of demand affects the outcome of an indirect tax. [15 marks]", "PED, tax incidence, consumption response and tax revenue.", "Inelastic demand permits a larger consumer price rise and smaller quantity fall, while elastic demand creates a larger behavioral response and may limit revenue.", "Consider supply elasticity, addiction or necessity, time horizon, avoidance, distributional effects and the policy's revenue or corrective objective.", "Attributing tax incidence to demand elasticity alone while ignoring supply elasticity.", ["ped", "tax_incidence", "distributional_effect"]],
      ["examine", "Examine why the price elasticity of demand for a product may change over time. [15 marks]", "Substitutes, habits, durable-goods adjustment and time horizon.", "Consumers can search, switch technology, alter routines or delay replacement over time, often increasing responsiveness, while loyalty or dependence may slow change.", "Assess the nature of the good, contract length, information, innovation and whether the price change is believed to be permanent.", "Assuming time always makes demand elastic regardless of available alternatives.", ["ped", "short_run_long_run", "consumer_response"]],
      ["to_what_extent", "To what extent can elasticity estimates improve government economic policy? [15 marks]", "PED, YED and XED as predictors of behavioral responses.", "Elasticities can inform tax revenue, subsidy, transport and health policy by estimating quantity and distributional effects.", "Judge against unstable estimates, market definition, changing behavior, equity aims, supply conditions and uncertainty about causal relationships.", "Treating a past elasticity estimate as a fixed natural constant.", ["elasticity", "policy_design", "assumptions"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "2.6",
    levelRelevance: SHARED,
    short: [
      ["define", "Define price elasticity of supply. [2 marks]", "The responsiveness of quantity supplied to a change in price, measured as the percentage change in quantity supplied divided by the percentage change in price.", "Confusing supply responsiveness with a shift in supply caused by costs.", ["pes", "definition"]],
      ["describe", "Describe perfectly inelastic supply. [2 marks]", "Quantity supplied does not change when price changes, so price elasticity of supply is zero.", "Describing a small but non-zero supply response as perfectly inelastic.", ["pes", "perfectly_inelastic"]],
      ["define", "Define excess capacity. [2 marks]", "The ability of a firm or industry to increase output using existing productive resources that are not fully utilized.", "Treating inventories of finished goods as identical to unused production capacity.", ["capacity", "supply_response"]],
    ],
    ten: [
      ["explain", "Explain why the price elasticity of supply for manufactured goods may increase over time. [10 marks]", "Time horizon, factor mobility, capacity and inventories.", "In the short run fixed capacity constrains output, while over time firms can hire, invest, enter and reorganize production in response to price.", "Assuming all manufacturing supply becomes perfectly elastic in the long run.", ["pes", "short_run_long_run", "investment"]],
      ["analyse", "Analyse how spare capacity may affect a firm's response to an increase in demand. [10 marks]", "Excess capacity, supply elasticity and market adjustment.", "A firm with idle capital and labor can expand output at relatively low additional cost, making supply more elastic and moderating price pressure.", "Assuming spare capacity guarantees unlimited output with no rising marginal costs.", ["capacity", "pes", "demand_shock"]],
      ["explain", "Explain why the supply of primary commodities is often price inelastic in the short run. [10 marks]", "Biological or extraction lags, fixed land and capacity, and inventories.", "Current output cannot quickly change because crops, herds or extraction projects take time, while storage may be limited.", "Claiming producers do not respond because they are unaware of higher prices.", ["pes", "commodities", "time_lags"]],
    ],
    fifteen: [
      ["evaluate", "Evaluate the importance of time in determining the price elasticity of supply. [15 marks]", "Time horizon, production lags, factor mobility and investment.", "More time usually permits capacity, entry and input adjustment, increasing responsiveness, but natural limits, regulation or scarce resources may remain binding.", "Compare industries, inventories, technology, expectations and whether the price signal is temporary or persistent.", "Treating time as the only determinant of supply elasticity.", ["pes", "short_run_long_run", "constraints"]],
      ["discuss", "Discuss how price elasticity of supply influences the effects of a sudden increase in demand. [15 marks]", "Supply elasticity and equilibrium adjustment.", "Elastic supply channels more of the demand increase into output, whereas inelastic supply channels more into price and producer revenue.", "Consider the time horizon, capacity, input markets, distributional consequences and whether higher prices induce future entry.", "Assuming producer welfare always rises more when supply is elastic.", ["pes", "demand_shock", "stakeholder_effect"]],
      ["examine", "Using real-world examples, examine policies that could make the supply of housing more responsive to price. [15 marks]", "Land-use rules, infrastructure, construction capacity, finance and supply elasticity.", "Planning reform, serviced land, skills investment or faster approvals can reduce constraints and expand the output response to price.", "Judge by local geography, time lags, infrastructure capacity, environmental costs, market power and unintended speculation.", "Assuming higher house prices alone quickly create new housing in constrained locations.", ["housing", "pes", "policy_design"]],
      ["to_what_extent", "To what extent does inelastic supply explain large price fluctuations in agricultural markets? [15 marks]", "Supply elasticity, demand shocks, weather and inventories.", "When supply cannot adjust, modest demand or harvest shocks cause large price changes, amplified by low demand elasticity and expectations.", "Assess storage, trade, futures markets, government support, product perishability and the relative size of demand and supply shocks.", "Attributing every agricultural price movement solely to farmers' short-run output response.", ["agriculture", "pes", "price_volatility"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "2.7",
    levelRelevance: SHARED,
    short: [
      ["define", "Define a price ceiling. [2 marks]", "A legally imposed maximum price, normally set below equilibrium if it is to be binding.", "Calling a price ceiling a minimum price guaranteed to producers.", ["price_ceiling", "government_intervention"]],
      ["define", "Define an indirect tax. [2 marks]", "A tax imposed on expenditure on goods or services, usually collected from producers or sellers.", "Confusing an indirect tax with a tax charged directly on income.", ["indirect_tax", "government_intervention"]],
      ["define", "Define a producer subsidy. [2 marks]", "A payment or financial assistance from government that lowers producers' effective costs or supports production.", "Describing a subsidy as a compulsory payment from producers to government.", ["subsidy", "government_intervention"]],
    ],
    ten: [
      ["explain", "Explain how a binding price ceiling may affect a market. [10 marks]", "Maximum prices, shortages and non-price allocation.", "A ceiling below equilibrium increases quantity demanded and reduces quantity supplied, creating a shortage that may lead to queues, rationing or informal markets.", "Assuming the controlled price automatically increases the amount available to consumers.", ["price_ceiling", "shortage", "unintended_consequence"]],
      ["analyse", "Analyse how a specific indirect tax may affect consumers and producers. [10 marks]", "Tax-induced supply shift, incidence and elasticity.", "The tax raises marginal cost and creates a wedge between prices paid and received, reducing quantity; incidence depends on relative demand and supply elasticities.", "Assuming the legally taxed side necessarily bears the full economic burden.", ["indirect_tax", "tax_incidence", "elasticity"]],
      ["explain", "Explain how a producer subsidy may affect market price and output. [10 marks]", "Subsidies, production costs and supply.", "A per-unit subsidy lowers effective marginal cost, shifts supply right, tends to reduce consumer price and increase output, with benefit split by elasticities.", "Assuming consumers always receive the full subsidy as an equal price reduction.", ["subsidy", "market_adjustment", "incidence"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate the use of price ceilings to make essential goods affordable. [15 marks]", "Maximum prices, affordability, shortages and alternative policies.", "A binding ceiling lowers the legal price for successful buyers but discourages supply and increases demand, creating rationing and quality or informal-market risks.", "Judge by supply response, enforcement, targeting, duration and comparison with transfers, subsidies or expanded public provision.", "Equating a lower controlled price with improved access for every low-income household.", ["price_ceiling", "equity", "government_failure"]],
      ["discuss", "Discuss whether indirect taxes are an effective way to reduce consumption of demerit goods. [15 marks]", "Indirect taxation, demand elasticity, external costs and information.", "A tax raises price and can internalize social costs, but consumption may respond weakly when demand is addictive or alternatives are limited.", "Consider tax design, regressivity, avoidance, use of revenue, long-run elasticity and complementary regulation or information.", "Assuming a higher tax always reduces total harm in the same proportion as sales.", ["indirect_tax", "demerit_good", "policy_effectiveness"]],
      ["examine", "Examine the likely effects of a minimum price in an agricultural market. [15 marks]", "Price floors, surpluses, producer income and government purchasing.", "A floor above equilibrium raises the legal price, reduces quantity demanded and increases quantity supplied, creating surplus unless output is restricted or purchased.", "Assess producer distribution, fiscal and storage costs, consumer effects, trade leakage, environmental incentives and policy alternatives.", "Assuming every farmer benefits equally from a price floor regardless of output or market access.", ["price_floor", "agriculture", "stakeholder_effect"]],
      ["to_what_extent", "To what extent can subsidies improve outcomes in markets for socially beneficial goods? [15 marks]", "Subsidies, positive externalities, access and government failure.", "Subsidies lower price or cost and expand consumption toward a socially preferred level, but poor targeting, inelastic supply or provider market power can absorb benefits.", "Judge additional consumption, equity, fiscal opportunity cost, quality, information and comparison with direct provision or regulation.", "Treating higher expenditure on a subsidized service as proof of proportionately greater social benefit.", ["subsidy", "merit_good", "government_failure"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "2.8",
    levelRelevance: SHARED,
    short: [
      ["define", "Define a negative externality of production. [2 marks]", "An uncompensated external cost imposed on third parties by the production of a good or service.", "Describing any private production cost paid by the firm as an externality.", ["negative_externality", "production"]],
      ["define", "Define a positive externality of consumption. [2 marks]", "An external benefit received by third parties from another person's consumption of a good or service.", "Confusing the consumer's own private benefit with a spillover to others.", ["positive_externality", "consumption"]],
      ["define", "Define a common-access resource. [2 marks]", "A rival resource from which it is difficult to exclude users, creating incentives for overuse.", "Treating a common-access resource as non-rival like a pure public good.", ["common_access", "resource_depletion"]],
    ],
    ten: [
      ["explain", "Explain why a negative production externality may cause market over-allocation of resources. [10 marks]", "Private and social costs, external cost and allocative efficiency.", "Producers base output on private cost and ignore harm to third parties, so market output exceeds the quantity where marginal social benefit equals marginal social cost.", "Assuming the external cost is already fully included in the producer's marginal private cost.", ["negative_externality", "overproduction", "allocative_efficiency"]],
      ["analyse", "Analyse how a tax on pollution may reduce a negative production externality. [10 marks]", "Corrective taxation and internalization of external cost.", "A tax linked to marginal external cost raises the polluter's private cost, encourages lower output or cleaner methods and can move the market toward the social optimum.", "Assuming any tax rate automatically equals marginal external cost at every output level.", ["pollution_tax", "internalization", "policy_design"]],
      ["explain", "Explain why an unregulated fishery may be overused. [10 marks]", "Common access, rivalry and individual incentives.", "Each fisher captures private benefit while sharing the depletion cost with all users, so individually rational harvesting can exceed the sustainable social level.", "Describing the problem as a lack of demand for fish rather than weak exclusion and shared depletion costs.", ["common_access", "tragedy_of_commons", "sustainability"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate the use of carbon taxes to reduce greenhouse-gas emissions. [15 marks]", "Negative externalities, carbon pricing and incentives.", "A carbon tax internalizes part of the external cost and encourages conservation and cleaner technology across many decisions.", "Judge the tax rate, demand and supply responses, monitoring, competitiveness, distribution, revenue use, policy credibility and alternatives.", "Assuming emissions fall by the same percentage as the tax raises fossil-fuel prices.", ["carbon_tax", "climate_change", "policy_effectiveness"]],
      ["discuss", "Discuss whether regulation is preferable to market-based policies for controlling pollution. [15 marks]", "Command-and-control regulation, taxes and tradable permits.", "Standards can guarantee limits for dangerous emissions, while price instruments provide flexibility and incentives to find lower-cost abatement.", "Compare information needs, enforcement, innovation, uncertainty over damages and costs, distribution and risk of regulatory capture.", "Treating all regulations as quantity bans and all market policies as voluntary.", ["regulation", "market_based_policy", "government_failure"]],
      ["examine", "Examine policies that could prevent the overuse of common-access resources. [15 marks]", "Property rights, quotas, community management, taxes and international cooperation.", "Effective exclusion or agreed harvesting limits can align individual incentives with resource renewal, while monitoring and sanctions support compliance.", "Consider local knowledge, enforcement cost, equity, migration of effort, scientific uncertainty and cross-border coordination.", "Assuming privatization always preserves a resource regardless of discount rates or enforcement.", ["common_access", "property_rights", "sustainability"]],
      ["to_what_extent", "To what extent can assigning property rights solve environmental externalities? [15 marks]", "Property rights, bargaining, transaction costs and externalities.", "Clear rights can enable negotiation or stewardship when parties and damages are identifiable, but high transaction costs and diffuse global harms limit bargaining.", "Judge by enforceability, number of parties, information, bargaining power, distribution, ecological thresholds and state capacity.", "Assuming an assigned right automatically produces the socially efficient amount of pollution.", ["property_rights", "transaction_costs", "environment"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "2.9",
    levelRelevance: SHARED,
    short: [
      ["define", "Define a public good. [2 marks]", "A good that is both non-rival in consumption and non-excludable.", "Calling any good supplied by government a public good regardless of its consumption characteristics.", ["public_good", "definition"]],
      ["define", "Define non-rivalry in consumption. [2 marks]", "One person's consumption does not reduce the amount or benefit available to others.", "Confusing non-rivalry with a zero price.", ["non_rivalry", "public_good"]],
      ["define", "Define the free-rider problem. [2 marks]", "People can benefit without paying, weakening the incentive for private providers to supply the good.", "Describing free riding simply as consumers looking for a lower price.", ["free_rider", "market_failure"]],
    ],
    ten: [
      ["explain", "Explain why a pure public good may be underprovided by a free market. [10 marks]", "Non-excludability, non-rivalry and the free-rider problem.", "Providers cannot reliably charge all beneficiaries, so private revenue understates total social benefit and profitable supply may be below the socially desirable level.", "Assuming non-rivalry alone prevents a provider from charging users.", ["public_good", "free_rider", "underprovision"]],
      ["analyse", "Analyse how government provision may address market failure in national flood protection. [10 marks]", "Public-good characteristics, collective finance and social benefit.", "Tax-funded coordinated provision can overcome free riding and account for widespread benefits that private sellers cannot capture.", "Assuming public provision reveals the exact socially optimal quantity without information or budget constraints.", ["public_good", "government_provision", "flood_protection"]],
      ["explain", "Explain how the characteristics of common-access resources and public goods create different forms of market failure. [10 marks]", "Rivalry, non-excludability, resource depletion and the free-rider problem.", "Common-access resources tend to be overused because each user's extraction reduces what remains, while pure public goods tend to be underprovided because providers cannot reliably charge all beneficiaries.", "Treating every non-excludable good as non-rival or assuming both cases lead to underproduction.", ["public_good", "common_access", "market_failure"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate government provision as a response to the underprovision of public goods. [15 marks]", "Public goods, collective finance and government provision.", "Tax funding can overcome free riding and coordinate supply, but government must still estimate social benefits, choose quality and control costs.", "Judge by information, accountability, fiscal opportunity cost, contracting options, local variation and risks of government failure.", "Assuming provision by government must mean direct production by government employees.", ["public_good", "government_provision", "government_failure"]],
      ["discuss", "Discuss whether all services with large social benefits should be provided free by government. [15 marks]", "Public goods, merit goods, positive externalities and rationing.", "Free provision may widen access and raise consumption, but many beneficial services are rival and excludable, so zero pricing can create congestion and fiscal costs.", "Distinguish public-good characteristics from merit arguments and consider targeting, user charges, equity, capacity and quality.", "Treating a positive externality as proof that a service is a pure public good.", ["public_good", "merit_good", "equity"]],
      ["examine", "Examine how new technology can change whether a good is excludable or rival. [15 marks]", "Public-good characteristics, digital access controls and congestion.", "Encryption, tolling or metering can make exclusion cheaper, while digital copying can reduce rivalry; congestion can make an initially non-rival service rival at peak use.", "Assess technological cost, legal enforcement, privacy, equity and whether exclusion improves efficiency or merely creates market power.", "Assuming rivalry and excludability are fixed labels determined only by who currently supplies the good.", ["technology", "excludability", "congestion"]],
      ["to_what_extent", "To what extent is the free-rider problem the main reason markets fail to provide public goods? [15 marks]", "Free riding, non-excludability, information and collective action.", "Inability to charge beneficiaries undermines private revenue, while uncertainty over benefits, coordination and political boundaries can further obstruct provision.", "Judge across local and global public goods, voluntary contributions, repeated interaction, philanthropy and government capacity.", "Assuming no private or community provision of public goods can ever occur.", ["free_rider", "collective_action", "market_failure"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "2.10",
    levelRelevance: HL,
    short: [
      ["define", "Define asymmetric information. [2 marks]", "A situation in which one party to an economic transaction has more or better relevant information than another.", "Describing ordinary uncertainty shared equally by both parties.", ["asymmetric_information", "definition"]],
      ["define", "Define adverse selection. [2 marks]", "Pre-contract information asymmetry that causes higher-risk or lower-quality participants to be disproportionately selected into a market.", "Confusing adverse selection with risky behavior that occurs after a contract is agreed.", ["adverse_selection", "information_failure"]],
      ["define", "Define moral hazard. [2 marks]", "Post-contract behavior in which protection from consequences or hidden actions increase a party's incentive to take risk or reduce care.", "Treating moral hazard as any action considered morally wrong.", ["moral_hazard", "information_failure"]],
    ],
    ten: [
      ["explain", "Explain how adverse selection may reduce the size of an insurance market. [10 marks]", "Hidden risk types, premiums and market unraveling.", "When insurers cannot distinguish risk, pooled premiums deter low-risk buyers, raising the average risk of those remaining and putting further upward pressure on premiums.", "Describing claims behavior after insurance is purchased rather than selection before contracting.", ["adverse_selection", "insurance", "market_unravelling"]],
      ["analyse", "Analyse how moral hazard may affect the market for health insurance. [10 marks]", "Insurance coverage, hidden action and incentives.", "Reduced personal cost can increase use of care or reduce prevention, raising insurers' costs and premiums unless contracts include monitoring, deductibles or co-payments.", "Assuming all additional use of insured health care is wasteful.", ["moral_hazard", "insurance", "incentives"]],
      ["explain", "Explain how signaling may reduce asymmetric information in a labour market. [10 marks]", "Signals, screening and worker quality.", "A costly and credible qualification or record can help productive workers distinguish themselves, allowing employers to make better wage and hiring decisions.", "Assuming any cheap claim is a credible signal regardless of whether types face different costs.", ["signaling", "labour_market", "screening"]],
    ],
    fifteen: [
      ["evaluate", "Evaluate policies designed to reduce adverse selection in insurance markets. [15 marks]", "Mandatory coverage, risk adjustment, disclosure, screening and subsidies.", "Broad participation can keep low-risk people in the pool, while better information and risk adjustment reduce incentives to avoid high-risk customers.", "Judge equity, privacy, administrative cost, cream-skimming, affordability and whether policies create new moral-hazard problems.", "Assuming risk-based pricing alone guarantees both efficiency and universal access.", ["adverse_selection", "insurance", "policy_design"]],
      ["discuss", "Discuss whether government regulation can solve information failure in markets for complex products. [15 marks]", "Disclosure, standards, licensing, warranties and behavioral limits.", "Mandatory information and quality rules can reduce hidden risks, but consumers may not process complex disclosures and regulators may lack timely knowledge.", "Consider enforcement, compliance cost, capture, innovation, third-party certification and the severity of harm from mistakes.", "Equating a larger quantity of disclosed information with better informed choice.", ["asymmetric_information", "regulation", "government_failure"]],
      ["examine", "Using real-world examples, examine how asymmetric information may affect labour-market outcomes. [15 marks]", "Worker quality, effort, signaling, screening and principal-agent problems.", "Employers may offer pooled wages or use credentials when productivity is hidden, while workers' hidden effort can require monitoring or incentive contracts.", "Assess signal accuracy, unequal access to credentials, probation, reputation, discrimination and changing information through employment.", "Treating all wage differences as evidence of asymmetric information.", ["labour_market", "signaling", "principal_agent"]],
      ["to_what_extent", "To what extent can reputation replace government intervention in markets with asymmetric information? [15 marks]", "Repeated interaction, reviews, brands, warranties and regulation.", "Reputation can discipline sellers when future business matters and feedback is reliable, but one-off transactions, fake reviews and severe hidden harms weaken it.", "Judge market repetition, traceability, platform incentives, consumer vulnerability, verification cost and consequences of low quality.", "Assuming a strong brand always provides accurate information about every product attribute.", ["reputation", "asymmetric_information", "regulation"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "2.11",
    levelRelevance: HL,
    short: [
      ["define", "Define market power. [2 marks]", "The ability of a firm to influence market price, output or other trading conditions rather than taking them as given.", "Equating market power solely with being a large firm by employee count.", ["market_power", "definition"]],
      ["define", "Define a barrier to entry. [2 marks]", "An obstacle that makes it difficult or costly for new firms to enter a market.", "Describing normal production costs faced equally by incumbents and entrants as a barrier by themselves.", ["barriers_to_entry", "market_structure"]],
      ["define", "Define price discrimination. [2 marks]", "Charging different prices to different consumers or market segments for the same product when the differences are not explained by cost.", "Calling any price difference price discrimination even when serving one group costs more.", ["price_discrimination", "market_power"]],
    ],
    ten: [
      ["explain", "Explain how barriers to entry can allow a firm to retain market power. [10 marks]", "Entry barriers, competition and supernormal profit.", "When profitable incumbents cannot be challenged easily, competitive entry and substitution are weakened, allowing price to remain above marginal cost.", "Assuming every profitable firm automatically has insurmountable entry barriers.", ["barriers_to_entry", "market_power", "profit"]],
      ["analyse", "Analyse how market power may affect price, output and consumer surplus. [10 marks]", "Profit-maximizing output under market power and allocative inefficiency.", "Restricting output relative to a more competitive outcome can raise price above marginal cost, transfer some surplus and create lost mutually beneficial trades.", "Assuming all producer gain from a higher price is itself a deadweight loss.", ["market_power", "consumer_surplus", "allocative_efficiency"]],
      ["explain", "Explain the conditions needed for a firm to practise price discrimination. [10 marks]", "Market power, identifiable segments, different elasticities and prevention of resale.", "The firm must separate customers with differing willingness to pay and stop lower-price purchases being resold to higher-price groups.", "Assuming any firm can discriminate merely by advertising two prices.", ["price_discrimination", "elasticity", "resale"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate the effects of market power on economic welfare. [15 marks]", "Price, output, surplus, efficiency, innovation and scale.", "Market power can raise price and restrict output, but profits and scale may finance innovation, quality or high fixed-cost services.", "Judge contestability, regulation, dynamic innovation, cost structure, price discrimination, consumer choice and distribution of gains.", "Assuming perfect competition is feasible and dynamically superior in every industry.", ["market_power", "welfare", "innovation"]],
      ["discuss", "Discuss whether competition policy should focus mainly on firm size. [15 marks]", "Market definition, concentration, conduct, entry barriers and consumer harm.", "Size may reflect scale economies or network effects and does not alone prove harmful power; entry barriers and exclusionary conduct may be more informative.", "Consider data control, potential competition, innovation, market definition, remedies and the risk of discouraging efficient growth.", "Treating market share in a narrowly chosen market as conclusive evidence of consumer harm.", ["competition_policy", "market_power", "government_failure"]],
      ["examine", "Examine the likely effects of price discrimination on consumers and producers. [15 marks]", "Market segmentation, elasticities, revenue and output.", "Discrimination can transfer surplus to producers and charge vulnerable groups more, but it may also expand output or fund access for price-sensitive consumers.", "Assess degree of discrimination, total output, cost coverage, fairness, arbitrage and which groups pay each price.", "Assuming price discrimination must reduce output relative to one-price monopoly.", ["price_discrimination", "stakeholder_effect", "equity"]],
      ["to_what_extent", "To what extent can regulation improve outcomes in a natural monopoly. [15 marks]", "Economies of scale, price regulation, public ownership and service quality.", "Price or rate-of-return controls can limit monopoly pricing, but regulators face information problems and may weaken cost-reduction or investment incentives.", "Judge the regulatory model, cost observability, quality standards, political independence, investment needs and alternatives such as franchising.", "Assuming marginal-cost pricing always covers the natural monopoly's total cost.", ["natural_monopoly", "regulation", "policy_effectiveness"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "2.12",
    levelRelevance: HL,
    short: [
      ["define", "Define economic equity. [2 marks]", "Fairness in the distribution of economic resources, opportunities or outcomes, judged according to a stated principle of fairness.", "Treating equity as identical to numerical equality in every circumstance.", ["equity", "definition"]],
      ["distinguish", "Distinguish between equity and equality. [2 marks]", "Equality concerns sameness of distribution or treatment, while equity concerns fairness and may justify different treatment or outcomes.", "Using equity and equality as exact synonyms without a fairness criterion.", ["equity", "equality"]],
      ["define", "Define horizontal equity in taxation. [2 marks]", "Taxpayers in similar economic circumstances should face similar tax treatment.", "Describing higher-income people paying more tax, which concerns vertical rather than horizontal equity.", ["horizontal_equity", "taxation"]],
    ],
    ten: [
      ["explain", "Explain why a competitive market may produce an inequitable distribution of income. [10 marks]", "Factor ownership, market rewards, inheritance and unequal opportunities.", "Market income reflects ownership and demand for productive resources rather than a social fairness rule, so initial endowments and unequal bargaining power can create persistent gaps.", "Assuming any income difference is necessarily inefficient or unfair under every definition of equity.", ["income_distribution", "factor_markets", "equity"]],
      ["analyse", "Analyse how a progressive income tax can reduce income inequality. [10 marks]", "Progressive taxation, disposable income and redistribution.", "Average tax rates rise with income, narrowing post-tax income differences; revenue may also finance transfers and services that benefit lower-income households.", "Assuming a progressive schedule guarantees lower inequality regardless of avoidance or benefit cuts.", ["progressive_tax", "redistribution", "inequality"]],
      ["explain", "Explain how unequal access to education may contribute to persistent income inequality. [10 marks]", "Human capital, productivity, wages and intergenerational transmission.", "Unequal education affects skills and employment opportunities, while family income and location feed back into access for the next generation.", "Assuming education alone determines every person's income.", ["education", "human_capital", "intergenerational_inequality"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate progressive taxation as a way to improve equity. [15 marks]", "Ability to pay, redistribution, incentives and tax administration.", "Progressive taxes reduce disposable-income gaps and finance public services, but behavioral responses, avoidance and design affect revenue and efficiency.", "Judge fairness principles, effective rather than statutory rates, labor and investment responses, administrative capacity and use of revenue.", "Assuming a higher top tax rate always raises total tax revenue and reduces inequality.", ["progressive_tax", "equity", "efficiency_equity_trade_off"]],
      ["discuss", "Discuss whether greater equality of income necessarily improves economic welfare. [15 marks]", "Income distribution, diminishing marginal utility, incentives and opportunity.", "Redistribution can raise welfare when extra income has greater value to poorer households, but policy design may affect incentives, growth and freedom of choice.", "Consider initial inequality, mobility, public goods, social cohesion, measurement and different principles of fairness.", "Treating equality of income as identical to equality of welfare or opportunity.", ["income_equality", "welfare", "trade_off"]],
      ["examine", "Examine policies that could improve equality of opportunity. [15 marks]", "Education, health, early-years support, anti-discrimination and access to finance.", "Reducing barriers to human-capital formation and participation can make outcomes less dependent on family background.", "Assess targeting, quality, time lags, geographic inequality, fiscal cost and whether formal access produces effective access.", "Assuming equal public spending per person guarantees equal opportunity.", ["equality_of_opportunity", "human_capital", "policy_design"]],
      ["to_what_extent", "To what extent should governments accept lower economic efficiency in pursuit of greater equity? [15 marks]", "Efficiency-equity trade-offs, redistribution and market incentives.", "Taxes and transfers can distort some choices, yet reduced poverty, better health, education and social stability may also improve productive efficiency.", "Judge marginal policy changes, starting inequality, policy design, administrative leakage, social preferences and short-run versus long-run effects.", "Assuming all redistribution reduces total output by definition.", ["efficiency_equity_trade_off", "redistribution", "short_run_long_run"]],
    ],
  }),
];
