import "server-only";
import { topicQuestionSet } from "./topic-set";

const SHARED = "shared_sl_hl" as const;
const HL = "hl_only" as const;

export const UNIT_4_QUESTIONS = [
  ...topicQuestionSet({
    topicCode: "4.1",
    levelRelevance: SHARED,
    short: [
      ["define", "Define comparative advantage. [2 marks]", "The ability to produce a good or service at a lower opportunity cost than another producer or country.", "Defining comparative advantage as producing more output with fewer absolute resources.", ["comparative_advantage", "definition"], HL],
      ["define", "Define absolute advantage. [2 marks]", "The ability to produce more output with the same resources, or the same output with fewer resources, than another producer.", "Defining absolute advantage by lower opportunity cost rather than higher productivity.", ["absolute_advantage", "definition"], HL],
      ["define", "Define the terms of trade. [2 marks]", "An index comparing a country's export prices with its import prices, commonly export prices divided by import prices times 100.", "Confusing the terms of trade with the trade balance or volume of exports.", ["terms_of_trade", "international_trade"], HL],
    ],
    ten: [
      ["explain", "Explain how specialization according to comparative advantage may increase total output. [10 marks]", "Opportunity costs, specialization and gains from trade.", "Resources shift toward goods with lower relative opportunity cost, allowing combined production and mutually beneficial consumption possibilities to expand.", "Assuming comparative advantage requires one country to have an absolute advantage.", ["comparative_advantage", "specialization", "gains_from_trade"], HL],
      ["analyse", "Analyse how international trade may increase competition in a domestic market. [10 marks]", "Import competition, market contestability, prices and efficiency.", "Access by foreign suppliers expands alternatives and disciplines domestic firms, encouraging lower costs, innovation or quality improvements.", "Assuming import competition benefits every domestic producer and worker.", ["trade", "competition", "productivity"]],
      ["explain", "Explain how economies of scale may create gains from international trade. [10 marks]", "Market size, specialization, average cost and variety.", "Export access expands potential output, allowing fixed costs to be spread and specialized production to lower unit costs, while consumers gain variety.", "Assuming all industries experience falling average cost without limit.", ["economies_of_scale", "trade", "market_size"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate the benefits of international trade for consumers. [15 marks]", "Prices, variety, quality, competition and real income.", "Imports and competition can lower prices and expand choice, raising real purchasing power, but adjustment losses, standards and dependence can affect consumers unevenly.", "Judge by market structure, exchange rates, product safety, income distribution, supply resilience and long-run productivity effects.", "Assuming lower import prices necessarily reflect a permanent welfare gain with no external costs.", ["trade", "consumer_welfare", "competition"]],
      ["discuss", "Discuss whether comparative advantage is sufficient to explain modern patterns of trade. [15 marks]", "Opportunity costs, factor endowments, scale, product differentiation and global value chains.", "Relative costs remain important, but scale economies, technology, institutions, strategic firms and fragmented production also shape trade.", "Assess model assumptions, transport costs, dynamic advantage, intra-industry trade and the role of policy and multinational enterprises.", "Rejecting comparative advantage because countries trade similar manufactured products.", ["comparative_advantage", "trade_patterns", "assumptions"], HL],
      ["examine", "Examine how greater openness to trade may affect economic growth. [15 marks]", "Specialization, competition, technology transfer, export demand and vulnerability.", "Trade can improve resource allocation, scale and access to capital goods, but specialization and external shocks can create volatility or lock-in.", "Consider institutions, export composition, learning, infrastructure, exchange rates, adjustment policy and environmental effects.", "Assuming a higher trade-to-GDP ratio by itself proves trade caused growth.", ["trade_openness", "growth", "technology_transfer"]],
      ["to_what_extent", "To what extent do the gains from trade depend on how they are distributed within a country? [15 marks]", "Aggregate welfare gains, factor-market adjustment and distribution.", "Trade can raise total surplus while import-competing workers or regions lose, so compensation and mobility determine whether gains translate into broad welfare improvement.", "Judge efficiency against equity, adjustment duration, social insurance, ownership, consumer gains and political sustainability.", "Assuming a positive national gain means every household is better off.", ["gains_from_trade", "distributional_effect", "stakeholder_effect"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "4.2",
    levelRelevance: SHARED,
    short: [
      ["define", "Define a tariff. [2 marks]", "A tax imposed on imported goods or services.", "Defining a tariff as a quantitative limit on imports.", ["tariff", "trade_protection"]],
      ["define", "Define an import quota. [2 marks]", "A legal quantitative limit on the amount or value of a good that may be imported during a period.", "Describing a quota as a tax collected on each imported unit.", ["quota", "trade_protection"]],
      ["define", "Define an export subsidy. [2 marks]", "Government financial support linked to producing or selling goods for export.", "Confusing an export subsidy with a tax on imported competitors.", ["export_subsidy", "trade_protection"]],
    ],
    ten: [
      ["explain", "Explain how a tariff affects the domestic market for an imported good. [10 marks]", "Tariff-inclusive import price, domestic demand, domestic supply and imports.", "A tariff raises the domestic price above the world price, reducing domestic consumption, increasing domestic production and lowering import volume.", "Assuming the tariff raises the world price by the full tax for a small importing country.", ["tariff", "imports", "market_adjustment"]],
      ["analyse", "Analyse how an import quota may affect domestic consumers and producers. [10 marks]", "Quantity restriction, domestic price and quota rent.", "Restricting imports reduces total market supply and raises domestic price, benefiting protected producers while consumers pay more and buy less.", "Assuming government necessarily receives quota rent as it would tariff revenue.", ["quota", "stakeholder_effect", "quota_rent"]],
      ["explain", "Explain how an export subsidy may affect domestic resource allocation. [10 marks]", "Producer incentives, exports, domestic price and opportunity cost.", "The subsidy draws resources into the supported export sector and may raise domestic price or output, while taxpayers fund production beyond the free-market level.", "Assuming subsidized exports impose no domestic fiscal or consumer cost.", ["export_subsidy", "resource_allocation", "government_failure"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate the effects of tariffs on an economy. [15 marks]", "Tariff protection, government revenue, consumers, producers and efficiency.", "Tariffs support import-competing output and revenue but raise prices, reduce consumption and create production and consumption inefficiencies.", "Judge country size, retaliation, time horizon, strategic aims, supply chains, distribution and whether protection enables adjustment.", "Counting transfers to producers and government entirely as net national losses.", ["tariff", "welfare", "stakeholder_effect"]],
      ["discuss", "Discuss whether import quotas are more effective than tariffs in restricting imports. [15 marks]", "Price versus quantity instruments, uncertainty and quota rents.", "A quota fixes the maximum import amount, while a tariff's import effect varies with demand and supply; quota allocation can create rents and corruption.", "Compare administrative capacity, changing market conditions, revenue, transparency, international rules and market power of license holders.", "Assuming a quota and tariff with the same initial import effect remain equivalent after demand changes.", ["quota", "tariff", "policy_comparison"]],
      ["examine", "Examine how trade protection may affect firms that use imported inputs. [15 marks]", "Input costs, competitiveness, supply chains and effective protection.", "Tariffs or quotas on intermediate goods raise downstream costs, potentially reducing exports, investment or employment even as upstream producers gain.", "Assess input substitutability, exchange rates, exemptions, market power, supply resilience and short-run versus long-run sourcing.", "Treating all domestic firms as protected beneficiaries of an import barrier.", ["trade_protection", "supply_chains", "stakeholder_effect"]],
      ["to_what_extent", "To what extent can subsidies achieve the objectives of trade protection at lower cost than tariffs? [15 marks]", "Production subsidies, tariffs, prices, fiscal cost and targeting.", "A targeted subsidy can support domestic production without raising consumer price as much, but requires taxation and risks persistence or capture.", "Judge the objective, fiscal capacity, information, spillovers, international rules, retaliation and whether support is temporary and conditional.", "Assuming subsidies have no opportunity cost because consumers pay a lower market price.", ["subsidy", "tariff", "policy_comparison"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "4.3",
    levelRelevance: SHARED,
    short: [
      ["define", "Define the infant-industry argument for trade protection. [2 marks]", "The claim that new domestic industries may need temporary protection until they gain scale, skills or productivity to compete internationally.", "Treating every old uncompetitive industry as an infant industry.", ["infant_industry", "trade_protection"]],
      ["define", "Define dumping in international trade. [2 marks]", "Selling exports in a foreign market below their normal value, such as below the home-market price or, under some definitions, below cost.", "Using dumping to mean any rise in the quantity of imports.", ["dumping", "trade_control"]],
      ["define", "Define trade retaliation. [2 marks]", "A government's imposition of trade restrictions in response to restrictions imposed by another country.", "Describing ordinary domestic competition as retaliation.", ["retaliation", "trade_conflict"]],
    ],
    ten: [
      ["explain", "Explain the infant-industry argument for temporary trade protection. [10 marks]", "Learning by doing, scale economies, finance constraints and future competitiveness.", "Temporary protection can provide time and market share for a new industry to build skills, reach scale and lower costs before competing without support.", "Assuming protection automatically creates productivity improvement without performance conditions.", ["infant_industry", "learning_by_doing", "time_lags"]],
      ["analyse", "Analyse how trade protection intended to preserve employment may affect an economy. [10 marks]", "Import competition, protected jobs, consumer costs and resource allocation.", "Protection can slow job losses in targeted sectors, but higher prices and input costs reduce real income and may harm employment elsewhere.", "Counting protected jobs without considering jobs affected in downstream or export sectors.", ["employment", "trade_protection", "stakeholder_effect"]],
      ["explain", "Explain why a country may use trade controls to protect national security. [10 marks]", "Strategic capacity, supply resilience and external dependence.", "Maintaining domestic capability or diverse suppliers can reduce vulnerability in essential goods, though broad protection may be costly.", "Treating every domestic product as strategically essential.", ["national_security", "supply_resilience", "trade_control"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate the infant-industry argument for trade protection. [15 marks]", "Dynamic comparative advantage, learning, scale and government failure.", "Protection may enable productivity gains where capital-market or learning spillovers exist, but identifying winners and withdrawing support are difficult.", "Judge evidence of learning, time limits, export discipline, consumer cost, capture, retaliation and viable future cost competitiveness.", "Assuming survival behind protection proves the industry has become internationally competitive.", ["infant_industry", "government_failure", "policy_effectiveness"]],
      ["discuss", "Discuss whether protecting domestic employment justifies restrictions on trade. [15 marks]", "Labour-market adjustment, distribution and trade gains.", "Protection can cushion concentrated losses and preserve communities, but raises consumer costs and can delay movement toward more productive activities.", "Consider unemployment type, adjustment speed, regional effects, retraining, retaliation, strategic capacity and less distortionary support.", "Assuming workers can move instantly and costlessly between industries.", ["employment", "trade_protection", "distributional_effect"]],
      ["examine", "Examine the economic case for trade protection on environmental grounds. [15 marks]", "Environmental externalities, carbon leakage, standards and discrimination.", "Border measures can address unpriced environmental costs or leakage, but may disguise protectionism and shift rather than reduce emissions.", "Assess measurement of embodied emissions, multilateral coordination, development equity, retaliation, consumption effects and alternative carbon pricing.", "Assuming imported goods are necessarily more environmentally damaging than domestic substitutes.", ["environment", "trade_protection", "externality"]],
      ["to_what_extent", "To what extent do the costs of trade protection exceed its benefits? [15 marks]", "Efficiency losses, revenue, strategic aims, distribution and dynamic effects.", "Protection usually raises domestic prices and misallocates resources, yet temporary adjustment, national security or externality objectives can create benefits.", "Judge instrument design, duration, country size, market failure, retaliation, stakeholder weights and feasible policy alternatives.", "Assuming all producer gains are net social benefits or all protection has identical effects.", ["trade_protection", "cost_benefit", "policy_design"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "4.4",
    levelRelevance: SHARED,
    short: [
      ["define", "Define a customs union. [2 marks]", "A group of countries that removes internal trade barriers and adopts a common external tariff toward non-members.", "Defining it as free internal trade without the common external trade policy.", ["customs_union", "economic_integration"]],
      ["define", "Define trade creation. [2 marks]", "The replacement of higher-cost domestic production by lower-cost imports from a partner after economic integration.", "Calling any increase in trade volume trade creation regardless of relative production cost.", ["trade_creation", "customs_union"], HL],
      ["define", "Define trade diversion. [2 marks]", "The replacement of lower-cost imports from a non-member by higher-cost imports from a member because of preferential trade treatment.", "Confusing trade diversion with consumers switching from imports to lower-cost domestic output.", ["trade_diversion", "customs_union"], HL],
    ],
    ten: [
      ["explain", "Explain how a customs union may create trade. [10 marks]", "Removal of internal tariffs, relative costs and resource allocation.", "Eliminating a tariff can make a lower-cost partner supplier cheaper than protected domestic production, expanding imports and improving allocation.", "Assuming all new partner imports are trade creation rather than possible diversion.", ["customs_union", "trade_creation", "efficiency"], HL],
      ["analyse", "Analyse how membership of a common market may affect labour mobility. [10 marks]", "Free movement, wage differences, skills and factor allocation.", "Reduced legal barriers allow workers to move toward higher returns and labour shortages, potentially raising output while affecting sending and receiving regions.", "Assuming legal mobility eliminates language, housing and qualification barriers.", ["common_market", "labour_mobility", "stakeholder_effect"]],
      ["explain", "Explain how economic integration may increase competition among firms. [10 marks]", "Larger markets, lower trade barriers, entry and scale.", "Domestic firms face more partner suppliers, which can reduce market power and encourage efficiency, while a larger market may also support consolidation.", "Assuming integration necessarily reduces concentration in every industry.", ["economic_integration", "competition", "economies_of_scale"]],
    ],
    fifteen: [
      ["evaluate", "Evaluate the likely economic effects of joining a customs union. [15 marks]", "Trade creation, trade diversion, scale, competition and tariff revenue.", "Members gain when lower-cost partner trade replaces domestic output, but may lose when preferences divert imports from more efficient outsiders.", "Judge pre-union tariffs, cost differences, market size, dynamic investment, bargaining power, adjustment and distribution among sectors.", "Assuming an increase in intra-union trade proves net welfare gain.", ["customs_union", "trade_creation", "trade_diversion"], HL],
      ["discuss", "Discuss whether deeper economic integration necessarily reduces national economic policy autonomy. [15 marks]", "Shared rules, monetary integration, fiscal policy and bargaining power.", "Common standards or currency arrangements restrict some independent choices, while collective influence and reduced spillovers may improve effective control over cross-border problems.", "Distinguish forms of integration and consider opt-outs, institutions, asymmetric shocks, credibility and democratic accountability.", "Treating a free-trade area as requiring a common monetary policy.", ["economic_integration", "policy_autonomy", "institutions"], HL],
      ["examine", "Examine how economic integration may affect less competitive regions within member countries. [15 marks]", "Agglomeration, labour mobility, investment and regional adjustment.", "Larger integrated markets may draw capital and skills toward productive centres, but transfers, market access and new investment can also support peripheral regions.", "Assess infrastructure, mobility costs, fiscal transfers, industrial structure, housing and the time needed for convergence.", "Assuming national gains from integration are distributed evenly across regions.", ["economic_integration", "regional_inequality", "distributional_effect"]],
      ["to_what_extent", "To what extent are dynamic gains more important than trade creation in determining the benefits of economic integration? [15 marks]", "Static allocation, scale, investment, competition and innovation.", "Trade creation yields immediate efficiency gains, while larger markets and credible rules may generate longer-run productivity, investment and innovation effects.", "Judge evidence, time horizon, market structure, institutions, adjustment cost and the counterfactual trade policy.", "Assuming dynamic gains are guaranteed and can be measured without a counterfactual.", ["dynamic_gains", "trade_creation", "short_run_long_run"], HL],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "4.5",
    levelRelevance: SHARED,
    short: [
      ["define", "Define exchange-rate depreciation. [2 marks]", "A fall in the value of a currency relative to another currency under a floating exchange-rate system.", "Using depreciation for an official reduction in a fixed exchange rate.", ["depreciation", "exchange_rate"]],
      ["define", "Define exchange-rate appreciation. [2 marks]", "A rise in the value of a currency relative to another currency under a floating exchange-rate system.", "Defining appreciation as a general rise in domestic prices.", ["appreciation", "exchange_rate"]],
      ["define", "Define a fixed exchange rate. [2 marks]", "An exchange-rate value or narrow range maintained by the authorities through intervention and supporting policies.", "Treating a fixed exchange rate as a currency value that can never be changed.", ["fixed_exchange_rate", "definition"]],
    ],
    ten: [
      ["explain", "Explain how an increase in demand for a country's exports may affect its exchange rate. [10 marks]", "Foreign-currency demand, export receipts and exchange-rate determination.", "Foreign buyers need the exporter's currency, shifting its demand right and tending to appreciate it under a floating system, other things equal.", "Assuming export demand changes the exchange rate by government decree.", ["exports", "currency_demand", "appreciation"]],
      ["analyse", "Analyse how currency depreciation may affect domestic inflation. [10 marks]", "Import prices, production costs, aggregate demand and expectations.", "Depreciation raises the domestic-currency cost of imports and imported inputs and may strengthen net exports, creating cost-push and demand pressure.", "Assuming every imported price rises instantly by the full exchange-rate percentage.", ["depreciation", "inflation", "pass_through"]],
      ["explain", "Explain how higher domestic interest rates may affect a floating exchange rate. [10 marks]", "Interest differentials, capital flows and currency demand.", "Higher relative returns may attract financial inflows and raise demand for the currency, causing appreciation, though expectations and risk can offset this.", "Assuming the exchange rate always appreciates when interest rates rise regardless of expected inflation or risk.", ["interest_rate", "capital_flow", "appreciation"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate whether currency depreciation improves a country's trade balance. [15 marks]", "Export and import prices, demand responses, contracts and adjustment.", "Depreciation makes exports cheaper abroad and imports dearer domestically, potentially improving net export revenue if quantities respond sufficiently.", "Judge qualitative price and quantity responses, time lags, invoicing currency, capacity, imported inputs and global demand; formal Marshall-Lerner conditions and a J-curve are not required.", "Assuming cheaper export prices automatically increase export revenue in domestic currency.", ["depreciation", "trade_balance", "elasticity"]],
      ["discuss", "Discuss the effects of currency appreciation on households and firms. [15 marks]", "Import prices, export competitiveness, real income and foreign-currency exposure.", "Appreciation lowers import costs and can raise consumers' real purchasing power, but squeezes exporters and import-competing firms.", "Compare net importers and exporters, hedging, market power, imported inputs, tourism, debt denomination and time horizon.", "Assuming all domestic firms lose when the currency appreciates.", ["appreciation", "stakeholder_effect", "competitiveness"]],
      ["examine", "Examine the advantages and disadvantages of a fixed exchange-rate system. [15 marks]", "Exchange-rate certainty, inflation discipline, reserves and policy autonomy.", "A credible peg can reduce transaction risk and anchor expectations, but defending it may require reserves, interest-rate changes and costly domestic adjustment.", "Assess credibility, reserve adequacy, trade patterns, capital mobility, asymmetric shocks and the suitability of the chosen parity.", "Assuming a fixed rate eliminates all currency risk or balance-of-payments pressure.", ["fixed_exchange_rate", "policy_autonomy", "stability"], HL],
      ["to_what_extent", "To what extent should a central bank intervene to limit exchange-rate volatility? [15 marks]", "Foreign-exchange intervention, expectations, reserves and macroeconomic objectives.", "Intervention can smooth disorderly moves and protect financial stability, but may conflict with monetary goals and fail against persistent market pressure.", "Judge the exchange-rate regime, source of volatility, pass-through, reserve cost, credibility, capital flows and whether the target is a level or pace of change.", "Assuming intervention can permanently set a currency value without supporting policies.", ["exchange_rate_intervention", "volatility", "central_bank"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "4.6",
    levelRelevance: SHARED,
    short: [
      ["define", "Define the current account of the balance of payments. [2 marks]", "The record of trade in goods and services, primary income and secondary income transfers between residents and the rest of the world.", "Defining it only as exports minus imports of goods.", ["current_account", "definition"]],
      ["define", "Define a current-account deficit. [2 marks]", "A negative current-account balance in which current external payments exceed current external receipts over a period.", "Equating the current-account deficit with the government's budget deficit.", ["current_account_deficit", "balance_of_payments"]],
      ["define", "Define the financial account of the balance of payments. [2 marks]", "The record of cross-border transactions in financial assets and liabilities, including direct and portfolio investment.", "Describing tax revenue and government expenditure accounts.", ["financial_account", "capital_flow"], HL],
    ],
    ten: [
      ["explain", "Explain how rapid domestic economic growth may lead to a current-account deficit. [10 marks]", "Income, import demand, capacity and competitiveness.", "Higher household and investment spending raises imports, while domestic capacity pressure may weaken export competitiveness, causing payments to grow faster than receipts.", "Assuming growth always reduces exports in absolute terms.", ["growth", "current_account_deficit", "imports"]],
      ["analyse", "Analyse how a persistent current-account deficit may be financed. [10 marks]", "Financial inflows, asset sales, borrowing and reserve changes.", "The accounting counterpart can include foreign direct or portfolio investment, external borrowing or reserve use, each changing claims between residents and foreigners.", "Treating financing as a separate event that need not balance international payments accounting.", ["current_account_deficit", "financial_account", "financing"], HL],
      ["explain", "Explain how improved productivity may affect a country's current-account balance. [10 marks]", "Unit costs, export competitiveness and import substitution.", "Higher productivity can lower relative costs or improve quality, supporting exports and domestic alternatives to imports, though stronger income and investment can also raise imports.", "Assuming productivity affects the current account only through a lower exchange rate.", ["productivity", "competitiveness", "current_account"]],
    ],
    fifteen: [
      ["evaluate", "Evaluate the view that a current-account deficit is harmful to an economy. [15 marks]", "External balance, financing, investment, debt and competitiveness.", "A deficit may finance productive investment or reflect strong growth, but persistent borrowing for consumption can increase vulnerability and future income outflows.", "Judge size, duration, financing composition, currency denomination, reserve status, productive capacity and investor confidence.", "Assuming every deficit means the country is insolvent or living beyond its means in the same way as a household.", ["current_account_deficit", "external_sustainability", "capital_flow"], HL],
      ["discuss", "Discuss policies a government might use to reduce a persistent current-account deficit. [15 marks]", "Expenditure reduction, expenditure switching and supply-side competitiveness.", "Fiscal or monetary restraint can reduce import demand, depreciation can switch spending, and productivity policy can improve export supply.", "Compare inflation, unemployment, elasticities, retaliation, implementation lags, distribution and whether the deficit reflects weak competitiveness or strong investment.", "Assuming import restrictions reduce the deficit without exchange-rate, retaliation or input-cost effects.", ["current_account_deficit", "policy_mix", "competitiveness"], HL],
      ["examine", "Examine how foreign direct investment may affect the balance of payments over time. [15 marks]", "Financial inflows, import demand, exports and primary income.", "Initial investment creates a financial inflow and may build export capacity, while imported capital goods and later profit remittances can worsen current-account components.", "Assess local sourcing, reinvested earnings, technology transfer, export orientation, financing structure and the time horizon.", "Counting the initial financial inflow as permanent current-account revenue.", ["fdi", "balance_of_payments", "short_run_long_run"], HL],
      ["to_what_extent", "To what extent can a persistent current-account surplus create economic problems? [15 marks]", "Current-account surpluses, domestic demand, exchange rates and international adjustment.", "A surplus may reflect competitiveness and foreign-asset accumulation, but it can also accompany weak domestic spending, currency pressure or dependence on external demand.", "Judge the cause, size and duration of the surplus, use of foreign earnings, exchange-rate regime, trading-partner effects and scope for rebalancing.", "Assuming every current-account surplus proves that domestic living standards and economic welfare are rising.", ["current_account_surplus", "external_balance", "policy_adjustment"], HL],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "4.7",
    levelRelevance: SHARED,
    short: [
      ["define", "Define sustainable development. [2 marks]", "Development that meets present needs without compromising the ability of future generations to meet their own needs.", "Defining sustainability only as continuous GDP growth.", ["sustainable_development", "definition"]],
      ["define", "Define renewable natural capital. [2 marks]", "Natural resources or ecosystems that can regenerate through natural processes if use does not exceed their renewal capacity.", "Assuming renewable resources cannot be depleted or degraded.", ["natural_capital", "renewable_resource"]],
      ["define", "Define intergenerational equity. [2 marks]", "Fairness in the distribution of resources, opportunities and environmental quality between present and future generations.", "Treating intergenerational equity as equality of income among people alive at the same time.", ["intergenerational_equity", "sustainability"]],
    ],
    ten: [
      ["explain", "Explain how overuse of natural resources may limit future economic development. [10 marks]", "Natural capital, depletion, productivity and intergenerational effects.", "Resource degradation can reduce future production, health, resilience and livelihoods, raising costs and narrowing future choices.", "Assuming resource extraction contributes nothing to current development or must always stop completely.", ["natural_capital", "resource_depletion", "intergenerational_equity"]],
      ["analyse", "Analyse how investment in clean public transport may support sustainable development. [10 marks]", "Public investment, transport externalities, accessibility and productive capacity.", "Reliable low-emission transport can reduce congestion and pollution, improve access to jobs and services, and raise productivity, although construction uses scarce resources.", "Assuming new transport infrastructure is sustainable regardless of usage, location or environmental cost.", ["public_transport", "sustainable_development", "infrastructure"]],
      ["explain", "Explain how secure property rights may affect the management of natural resources. [10 marks]", "Ownership, stewardship, investment and common access.", "Secure and enforceable rights can give users an incentive to preserve future yields, though short time horizons or unequal rights can still produce overuse.", "Assuming private ownership always maximizes long-run environmental value.", ["property_rights", "natural_resources", "institutions"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate market-based policies for achieving environmentally sustainable development. [15 marks]", "Environmental taxes, tradable permits, subsidies and externalities.", "Price signals can reward low-cost abatement and innovation, but effectiveness depends on monitoring, price level, market design and access to alternatives.", "Judge environmental certainty, distribution, administrative capacity, volatility, political durability and comparison with standards or public investment.", "Assuming a market-based instrument leaves environmental outcomes entirely to an unregulated market.", ["market_based_policy", "sustainable_development", "policy_effectiveness"]],
      ["discuss", "Discuss whether economic growth can be environmentally sustainable. [15 marks]", "Growth, resource intensity, technology, consumption and ecological limits.", "Cleaner technology and structural change may decouple output from some impacts, while rebound effects and absolute resource limits challenge indefinite material expansion.", "Distinguish relative from absolute decoupling and consider income level, policy, consumption patterns, trade displacement and time horizon.", "Assuming lower emissions per unit of GDP necessarily means total environmental pressure is falling.", ["growth", "sustainability", "decoupling"]],
      ["examine", "Examine how a transition to renewable energy may affect economic development. [15 marks]", "Energy access, investment, employment, import dependence and transition costs.", "Renewables can reduce pollution and fuel-import exposure and expand access, but require capital, grids, storage, skills and management of displaced workers.", "Assess resource endowments, reliability, financing, distribution, local supply chains, policy credibility and short-run versus long-run costs.", "Assuming renewable energy has zero environmental or opportunity cost.", ["renewable_energy", "development", "just_transition"]],
      ["to_what_extent", "To what extent should present generations bear the cost of protecting natural capital for the future? [15 marks]", "Intergenerational equity, discounting, uncertainty and irreversible loss.", "Current protection can avoid irreversible damage and preserve future productive and welfare options, but also uses resources that could reduce present deprivation.", "Judge urgency, reversibility, income levels, discount rates, distribution within generations, uncertainty and burden-sharing between countries.", "Treating present and future generations as internally uniform groups with identical resources.", ["intergenerational_equity", "natural_capital", "trade_off"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "4.8",
    levelRelevance: SHARED,
    short: [
      ["define", "Define economic development. [2 marks]", "A multidimensional improvement in living standards and well-being, including income, health, education and opportunities.", "Defining development only as an increase in total real GDP.", ["economic_development", "definition"]],
      ["define", "Define the Human Development Index. [2 marks]", "A composite index combining indicators of health, education and income to summarize average human development.", "Describing it as a measure based only on GDP per capita.", ["hdi", "development_measurement"]],
      ["define", "Define purchasing-power parity. [2 marks]", "An exchange-rate conversion designed to equalize the purchasing power of currencies by accounting for differences in price levels.", "Treating purchasing-power parity as the current market exchange rate.", ["ppp", "international_comparison"]],
    ],
    ten: [
      ["explain", "Explain why gross national income per capita may not accurately measure economic development. [10 marks]", "Average income, distribution, non-market activity and multidimensional welfare.", "An average can conceal inequality and omits health, education, security, environmental quality and much informal or unpaid production.", "Assuming income has no relevance to development because it is incomplete.", ["gni_per_capita", "development_measurement", "inequality"]],
      ["analyse", "Analyse why purchasing-power-parity income measures may improve international comparisons. [10 marks]", "Price-level differences and real purchasing power.", "PPP conversion values income by the amount of a comparable basket it can buy, avoiding distortions from volatile market exchange rates and different local prices.", "Assuming one national price index captures every household's consumption accurately.", ["ppp", "income_comparison", "data_limitations"]],
      ["explain", "Explain how gender inequality may reduce measured and unmeasured development outcomes. [10 marks]", "Access to education, health, employment, income and agency.", "Restricted opportunities reduce human-capital use and household welfare, while unpaid work and limited voice may be missed by income statistics.", "Assuming gender inequality affects only women's recorded wages.", ["gender_inequality", "development", "measurement"]],
    ],
    fifteen: [
      ["evaluate", "Evaluate the usefulness of the Human Development Index for comparing development. [15 marks]", "Composite health, education and income indicators.", "HDI broadens comparison beyond income and is transparent, but national averages, limited dimensions and data quality conceal distribution and other freedoms.", "Judge the purpose, weighting, inequality, environmental sustainability, gender, subnational variation and use of complementary indicators.", "Assuming a composite index objectively determines one complete ranking of human welfare.", ["hdi", "development_measurement", "data_limitations"]],
      ["discuss", "Discuss whether income per capita remains the most useful single indicator of development. [15 marks]", "Income, consumption possibilities and multidimensional development.", "Income supports material choice and often correlates with health and education, but distribution, public services and non-market conditions alter lived outcomes.", "Assess data availability, PPP conversion, informal activity, inequality, sustainability and the question being asked of the indicator.", "Rejecting income measures entirely because they are not comprehensive.", ["income_per_capita", "development_measurement", "trade_off"]],
      ["examine", "Examine the difficulties of measuring poverty across countries. [15 marks]", "Absolute and relative thresholds, PPP, household data and multidimensional deprivation.", "Different prices, needs, survey quality and informal resources make a common monetary line imperfect, while relative lines answer a different question.", "Consider household composition, rural self-provision, regional prices, transient versus persistent poverty and multidimensional measures.", "Assuming one nominal currency amount represents the same living standard everywhere.", ["poverty_measurement", "ppp", "data_limitations"]],
      ["to_what_extent", "To what extent should development indicators include environmental sustainability. [15 marks]", "Current human outcomes, natural capital and intergenerational welfare.", "Income, health and education gains may be fragile if achieved by depleting ecosystems, so adjusted indicators can reveal whether development is maintainable.", "Judge measurement feasibility, double counting, national responsibility, future uncertainty and whether dashboards are preferable to one composite index.", "Assuming present human development and environmental protection can be summarized without value judgements.", ["development_measurement", "sustainability", "intergenerational_equity"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "4.9",
    levelRelevance: SHARED,
    short: [
      ["define", "Define a poverty cycle. [2 marks]", "A self-reinforcing process in which low income limits saving and investment in human or physical capital, helping to keep future income low.", "Describing poverty as a one-time fall in income with no feedback mechanism.", ["poverty_cycle", "development_barrier"]],
      ["define", "Define capital flight. [2 marks]", "A large movement of privately owned financial capital out of a country, often because of risk, instability or expected loss.", "Calling payment for normal imported goods capital flight.", ["capital_flight", "financial_flow"]],
      ["define", "Define infrastructure. [2 marks]", "The foundational physical and institutional systems that support economic activity, such as transport, energy, communications and water networks.", "Restricting infrastructure to factories owned by private firms.", ["infrastructure", "development_barrier"]],
    ],
    ten: [
      ["explain", "Explain how low household income can perpetuate a poverty cycle. [10 marks]", "Income, saving, nutrition, health, education and productivity.", "Low income restricts investment in skills, health and assets, keeping productivity and earning capacity low in the next period or generation.", "Assuming poor households simply choose not to save despite binding subsistence needs.", ["poverty_cycle", "human_capital", "intergenerational_effect"]],
      ["analyse", "Analyse how weak infrastructure may limit economic development. [10 marks]", "Transport, energy, communications, market access and productivity.", "Unreliable networks raise transaction and production costs, isolate households and firms, deter investment and constrain access to schools and health services.", "Assuming infrastructure affects development only by increasing government construction employment.", ["infrastructure", "productivity", "market_access"]],
      ["explain", "Explain how corruption may act as a barrier to economic development. [10 marks]", "Institutions, public spending, uncertainty, entry and trust.", "Bribes and diversion raise costs, weaken services and property rights, distort project selection and deter productive investment.", "Assuming every low-income country has the same form or level of corruption.", ["corruption", "institutions", "investment"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate the importance of education as a condition for economic development. [15 marks]", "Human capital, productivity, health, institutions and opportunity.", "Education can raise skills, adaptability and participation and produce wider social benefits, but quality and complementary jobs, health and infrastructure determine returns.", "Judge level and type of education, access, gender, migration, labour demand, governance, time lags and opportunity cost.", "Assuming enrollment rates measure learning or guarantee formal employment.", ["education", "development_barrier", "human_capital"]],
      ["discuss", "Discuss whether weak institutions are the main barrier to economic development. [15 marks]", "Property rights, governance, state capacity, conflict and complementary constraints.", "Reliable institutions support investment and public services, but geography, health, infrastructure, global markets and historical conditions can also bind.", "Assess causality, institutional diversity, reform sequencing, informal institutions and interaction with resources and external shocks.", "Treating institutions as one variable that can be changed quickly without political distributional effects.", ["institutions", "development_barrier", "governance"]],
      ["examine", "Examine how dependence on primary commodities may hinder economic development. [15 marks]", "Price volatility, terms of trade, value added, fiscal revenue and diversification.", "Commodity dependence exposes incomes and budgets to shocks and may limit learning, while resource revenue can also finance infrastructure and human capital.", "Judge commodity type, stabilization, governance, local linkages, exchange-rate effects, environmental costs and diversification policy.", "Assuming every commodity-exporting economy necessarily grows slowly.", ["commodity_dependence", "price_volatility", "diversification"]],
      ["to_what_extent", "To what extent does limited access to finance constrain small firms in developing economies? [15 marks]", "Credit markets, collateral, information, investment and informality.", "Credit constraints prevent profitable equipment, inventory or training investments, but demand, skills, infrastructure and regulation may be equally important.", "Assess mobile finance, microcredit, interest costs, risk, gender, firm capability and whether finance is used productively.", "Assuming any increase in lending automatically creates successful enterprises and development.", ["access_to_finance", "small_firms", "asymmetric_information"]],
    ],
  }),
  ...topicQuestionSet({
    topicCode: "4.10",
    levelRelevance: SHARED,
    short: [
      ["define", "Define foreign direct investment. [2 marks]", "Cross-border investment that gives an investor a lasting interest and significant influence or control in an enterprise.", "Treating any purchase of foreign shares as direct investment regardless of control.", ["fdi", "development_strategy"]],
      ["define", "Define microfinance. [2 marks]", "Small-scale financial services, such as loans and savings, provided to people or firms with limited access to conventional banking.", "Defining microfinance as grants that never need repayment.", ["microfinance", "financial_inclusion"]],
      ["define", "Define export promotion. [2 marks]", "Policies intended to increase the competitiveness, capacity or market access of domestic exporting firms.", "Treating export promotion as a policy to reduce all imports by quota.", ["export_promotion", "development_strategy"]],
    ],
    ten: [
      ["explain", "Explain how foreign direct investment may promote economic development. [10 marks]", "Capital formation, employment, technology, skills and market access.", "FDI can add productive capacity and transfer knowledge or export links, creating income and tax revenue when local connections are strong.", "Assuming the full value of foreign investment becomes local household income.", ["fdi", "technology_transfer", "development"]],
      ["analyse", "Analyse how microfinance may affect poverty and economic opportunity. [10 marks]", "Credit access, enterprise investment, consumption smoothing and risk.", "Small loans or savings services can fund assets and stabilize income, but high costs, weak demand or household debt can limit poverty reduction.", "Assuming every borrower is an entrepreneur with a high-return investment opportunity.", ["microfinance", "poverty", "financial_inclusion"]],
      ["explain", "Explain how export promotion may support economic growth and development. [10 marks]", "External demand, scale, foreign exchange, learning and diversification.", "Export growth can expand markets, earn foreign currency and encourage productivity, while development effects depend on value added, wages and local linkages.", "Assuming export revenue is identical to domestic value added.", ["export_promotion", "growth", "diversification"]],
    ],
    fifteen: [
      ["evaluate", "Using real-world examples, evaluate foreign direct investment as a development strategy. [15 marks]", "Capital, employment, technology transfer, profits and government bargaining.", "FDI can relieve capital and skill constraints and connect firms to markets, but profit remittances, enclaves, tax concessions and environmental harm may limit net benefits.", "Judge sector, local linkages, labour standards, competition, technology absorption, tax design, governance and the counterfactual investment.", "Assuming all foreign ownership either exploits the host country or benefits it automatically.", ["fdi", "development_strategy", "stakeholder_effect"]],
      ["discuss", "Discuss whether aid is an effective way to promote economic development. [15 marks]", "Humanitarian and development aid, public goods, capacity and dependency.", "Well-targeted aid can finance health, infrastructure and institutions where domestic resources are scarce, but volatility, donor priorities and weak accountability reduce impact.", "Consider aid type, local ownership, conditionality, fungibility, emergency versus long-run goals, governance and evaluation evidence.", "Treating all aid as identical cash transfers between governments.", ["foreign_aid", "development_strategy", "policy_effectiveness"]],
      ["examine", "Examine the role of trade policy in a country's development strategy. [15 marks]", "Export promotion, diversification, selective protection and global market access.", "Trade openness can support scale and technology, while temporary targeted support may address learning failures; both require complementary capability and institutions.", "Assess sequencing, exchange rates, infrastructure, market access, global value chains, policy discipline, retaliation and distribution.", "Assuming the same degree of openness is optimal for every country at every development stage.", ["trade_policy", "development_strategy", "policy_mix"]],
      ["to_what_extent", "To what extent should development strategies prioritize small domestic enterprises over large-scale projects? [15 marks]", "Employment, productivity, scale, linkages and access to finance.", "Small firms may spread income and create flexible local employment, while large projects can supply infrastructure, technology and scale unavailable to fragmented producers.", "Judge sector, financing, spillovers, governance, market access, environmental and social cost, and complementarity rather than a simple either-or choice.", "Assuming small firms are always labour-intensive and equitable or large projects always create broad spillovers.", ["small_enterprise", "large_scale_investment", "policy_comparison"]],
    ],
  }),
];
