-- Aptly server authority boundary.
--
-- Apply before 0008_ai_usage_reservations.sql. This migration deliberately
-- fails closed during a rolling release: once applied, old browser-authority
-- code can no longer create or update attempts/practice rows.

-- Durable request identity for server-created rows. Legacy rows remain NULL.
alter table public.attempts
  add column if not exists idempotency_key uuid;

create unique index if not exists attempts_user_idempotency_idx
  on public.attempts (user_id, idempotency_key)
  where idempotency_key is not null;

alter table public.practice_questions
  add column if not exists idempotency_key uuid,
  add column if not exists authority_version smallint;

-- Rows created before this boundary were generated by the existing server
-- route. Preserve them, but give new writes no default: only trusted server
-- code can knowingly provide the marker.
update public.practice_questions
set authority_version = 1
where authority_version is null;

alter table public.practice_questions
  alter column authority_version set not null,
  alter column authority_version drop default;

alter table public.practice_questions
  drop constraint if exists practice_questions_authority_version_chk;

alter table public.practice_questions
  add constraint practice_questions_authority_version_chk
  check (authority_version = 1);

create unique index if not exists practice_questions_user_idempotency_idx
  on public.practice_questions (user_id, idempotency_key)
  where idempotency_key is not null;

-- Diagram evidence is a small, exact, feedback-only JSON document. The raw
-- image, a URL/reference to it, EXIF, storage keys, arbitrary nested objects,
-- and unexpected fields are all rejected by the database as a final barrier.
create or replace function public.is_valid_diagram_evidence(value jsonb)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select
    jsonb_typeof(value) = 'object'
    and jsonb_object_length(value) = 7
    and value ?& array[
      'version',
      'status',
      'graphTypeObserved',
      'relevanceToQuestion',
      'elements',
      'consistencyWithAnswer',
      'improvements'
    ]
    and value->'version' = '1'::jsonb
    and value->>'status' in (
      'reviewed_clearly', 'partially_readable', 'unable_to_assess'
    )
    and (
      value->'graphTypeObserved' = 'null'::jsonb
      or (
        jsonb_typeof(value->'graphTypeObserved') = 'string'
        and char_length(value->>'graphTypeObserved') between 1 and 120
      )
    )
    and value->>'relevanceToQuestion' in (
      'appears_relevant', 'appears_unrelated', 'unclear'
    )
    and value->>'consistencyWithAnswer' in (
      'supports', 'conflicts', 'unclear', 'not_checked'
    )
    and jsonb_typeof(value->'elements') = 'array'
    and jsonb_array_length(value->'elements') between 0 and 7
    and not exists (
      select 1
      from jsonb_array_elements(value->'elements') as item(element)
      where jsonb_typeof(element) <> 'object'
        or jsonb_object_length(element) <> 2
        or not (element ?& array['element', 'observed'])
        or element->>'element' not in (
          'axes_labels', 'curve_labels', 'equilibrium', 'shift_arrows',
          'new_equilibrium', 'welfare_areas', 'annotations'
        )
        or element->>'observed' not in ('visible', 'unclear', 'not_visible')
    )
    and (
      select count(*) = count(distinct element->>'element')
      from jsonb_array_elements(value->'elements') as item(element)
    )
    and jsonb_typeof(value->'improvements') = 'array'
    and jsonb_array_length(value->'improvements') between 0 and 2
    and not exists (
      select 1
      from jsonb_array_elements(value->'improvements') as item(improvement)
      where jsonb_typeof(improvement) <> 'string'
        or char_length(improvement #>> '{}') not between 1 and 280
    )
    and octet_length(value::text) <= 16384
    and (
      value->>'status' <> 'unable_to_assess'
      or (
        value->'graphTypeObserved' = 'null'::jsonb
        and value->>'relevanceToQuestion' = 'unclear'
        and jsonb_array_length(value->'elements') = 0
        and value->>'consistencyWithAnswer' = 'not_checked'
        and jsonb_array_length(value->'improvements') = 0
      )
    )
    and (
      value->>'status' = 'reviewed_clearly'
      or value->>'consistencyWithAnswer' = 'not_checked'
    )
    and value::text !~* '(data:|blob:|s3:|gs:|base64|https?://|file:/{0,2}|image/(png|jpe?g|gif|webp|heic|tiff?|bmp)|storage[_ /-]?(key|path|object|reference|bucket)|exif|gps|thumbnail|[a-z0-9+/]{80,}={0,2}|\.(png|jpe?g|gif|webp|heic|tiff?|bmp)([^a-z0-9]|$))';
$$;

revoke all on function public.is_valid_diagram_evidence(jsonb) from public, anon, authenticated;

alter table public.attempts
  drop constraint if exists attempts_diagram_evidence_valid_chk;

-- NOT VALID avoids scanning unknown legacy rows while still enforcing the
-- constraint for every new insert/update. Validate later after the documented
-- compatibility query returns no rows.
alter table public.attempts
  add constraint attempts_diagram_evidence_valid_chk
  check (
    diagram_evidence is null
    or public.is_valid_diagram_evidence(diagram_evidence)
  ) not valid;

-- Browser clients may read and delete their own attempts, but authoritative
-- creation/attachment is server-only. Removing UPDATE also removes the prior
-- relationship-link ownership weakness from the browser surface.
revoke insert, update on table public.attempts from authenticated;
drop policy if exists "insert_own_attempts" on public.attempts;
drop policy if exists "update_own_attempts" on public.attempts;
revoke execute on function public.owns_attempt(uuid) from authenticated;
revoke execute on function public.owns_practice_question(uuid) from authenticated;

-- Generated practice is likewise server-authoritative. Existing own-row
-- SELECT/DELETE behavior is intentionally retained.
revoke insert, update on table public.practice_questions from authenticated;
drop policy if exists "insert_own_practice_questions" on public.practice_questions;

-- The four routes now use one private reservation ledger (migration 0008).
-- Retain legacy rows for audit/compatibility but remove browser manipulation.
revoke all on table public.scan_extraction_usage from authenticated;
revoke all on table public.diagram_review_usage from authenticated;
drop policy if exists "select_own_scan_usage" on public.scan_extraction_usage;
drop policy if exists "insert_own_scan_usage" on public.scan_extraction_usage;
drop policy if exists "select_own_diagram_usage" on public.diagram_review_usage;
drop policy if exists "insert_own_diagram_usage" on public.diagram_review_usage;

comment on column public.attempts.idempotency_key is
  'Server-issued grade operation key; NULL only for legacy rows.';
comment on column public.practice_questions.authority_version is
  'Trusted generation marker. Value 1 is supplied explicitly by server code.';
comment on function public.is_valid_diagram_evidence(jsonb) is
  'Fail-closed exact-shape and payload validation for feedback-only evidence.';
